### ISSUE TITLE
flv直播模式，Safari浏览器播放会卡在第一帧

### ISSUE THREAD

**Issue by jinyang1994** [Chimeejs/chimee#100]
####  使用的版本：
chimee 0.9.3

#### 使用的kernel：
chimee-kernel-flv 1.4.10

#### 使用的插件：
chimee-plugin-center-state 0.0.10

#### 使用的config：
```javascript
import Chimee from 'chimee';
import ChimeeFlv from 'chimee-kernel-flv';
import chimeePluginCenterState from 'chimee-plugin-center-state';

Chimee.install(chimeePluginCenterState);

const player = new Chimee({
  wrapper: '',
  src: '',
  isLive: true,
  autoplay: true,
  controls: true,
  box: 'flv',
  kernels: {
    flv: {
      handler: ChimeeFlv,
      hasVideo: true,
      hasAudio: true,
    },
  },
  plugin: [
    {
      name: chimeePluginCenterState.name,
      errorTips: 'Server error, please reload the page.',
    },
  ],
});
```

#### 可复现的推流地址：
http://20942.liveplay.myqcloud.com/live/20942_8c98bbb420e711e89548f23c91a79606.flv
（如果不可用联系我重开）

#### 预期的效果：
播放器加载资源后播放。

#### 实际的效果：
自动播放时：播放器一直处于loading状态，并且卡在第一帧，有时会有声音。
出现播放按钮时：点击播放按钮，一直卡在第一帧。

这种情况如果想正常播放需要过15s左右，点击controls上的前进15s按钮，才可以继续播放。

**Comment by toxic-johann** [comment]
现在这个流在我本地不能播放耶。

**Comment by jinyang1994** [comment]
稍等，我换个地址

**Comment by songguangyu** [comment]
@jinyang1994 safari 需要静音播放

**Comment by jinyang1994** [comment]
http://20942.liveplay.myqcloud.com/live/20942_ad43f92a20ea11e8a025f23c91a79606.flv

**Comment by jinyang1994** [comment]
@songguangyu 我是在PC端也需要静音播放么？而且我发现，只有在iOS拍摄下，会出现卡主的问题，Android不会出现上面的问题。

**Comment by jinyang1994** [comment]
那我需要声音怎么办？是先设置声音为0，然后开始播放时再开启声音？

**Comment by songguangyu** [comment]
没有办法，这个是苹果公司定的，我们开发者也无力改变这个问题。如果实在有必要 可以考虑使用flash。

**Comment by jinyang1994** [comment]
不过我有一个地方很疑惑，为什么Android拍摄的直播流在Safari就可以正常播放，但是iOS拍摄的就会出现这个问题。

**Comment by songguangyu** [comment]
意思是不是静音播放的问题？ 安卓和Ios是同一套推流工具吗？ 编码方式一样吗？

**Comment by toxic-johann** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fp2xdxih43j30s5042q4h.jpg)

提供一个可以跨域的流吧。

**Comment by jinyang1994** [comment]
Android和iOS采用的都是腾讯直播提供的推流工具。但是两个平台采用的编码策略是不一样的，Android优先采用软编，而iOS优先采用硬编。
我重新发一个推流地址。http://20942.liveplay.myqcloud.com/live/20942_6c89add220ed11e8a025f23c91a79606.flv

**Comment by jinyang1994** [comment]
我们试过iOS软编，还是不行

**Comment by songguangyu** [comment]
那如果使用第三方推流工具呢？ 腾讯的推流工具我们还没使用过。

**Comment by jinyang1994** [comment]
我们也是第一次做直播，还没考虑使用别的推流工具。

**Comment by songguangyu** [comment]
我稍后尝试一下 看看有啥不同

**Comment by jinyang1994** [comment]
@songguangyu 非常感谢您的支持🙏
