### ISSUE TITLE
当chimee内部插件需要嵌套一个chimee播放器的时候，播放器destroy的时候会出现问题

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#101]
![image](https://user-images.githubusercontent.com/1788280/37073808-0da673be-2204-11e8-9d54-b1b59afcb04f.png)
需求大概如图所示，播放器内部插件集成的组件内部，也引入了一个chimee播放器，此时destroy的时候会出现问题，具体示例代码稍候补充

**Comment by toxic-johann** [comment]
好像没法复现这个逻辑。https://github.com/Chimeejs/chimee/blob/next/demo/chimee-in-plugin/index.js

如果插件内的 chimee 先 destroy，主 player 没受到影响。

如果主 player 先 destroy，则所有插件都被销毁。是希望该插件留存？
