### ISSUE TITLE
希望能增加kernel层自定义事件的上报机制

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#102]
如题，有些场景需要内核上报一些监控信息等，目前事件类型写死在了chimee-kernel以及chimee内的kernenEvents里，希望能够放开这块限制
PS：目前chimee与chimee-kernel都分别维护了一个kernenEvents，希望这块还是能统一一下😂

**Comment by skyline0705** [comment]
可以考虑 chimee-kernel 提供一个事件列表 供chimee读取合并。
-------------------------------------------------------------------------
@songguangyu 

这块个人建议不要写死，毕竟如果有定制需求的时候，比如内部一些上报机制，还是需要单独的事件处理的，希望还是放开事件注册，而不是只支持默认list内的事件

**Comment by songguangyu** [comment]
@skyline0705 嗯 这样可能会更好。

**Comment by toxic-johann** [comment]
已完成，可参照[此处](https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha)下载 alpha 版进行试用。
