### ISSUE TITLE
为什么无法再手机端播放m3u8格式的直播？

### ISSUE THREAD

**Issue by cruelwolfking** [Chimeejs/chimee#103]
在PC端播放很正常，在苹果手机则无法播放，安卓苹果微信内核浏览器也都不可以播放。安卓浏览器可以播放

**Comment by toxic-johann** [comment]
请尽量给出如 codepen 上的复现地址，或者错误信息、所用版本，相关代码等更多信息。

**Comment by cruelwolfking** [comment]
<script>
  import axios from 'axios';
  import Chimee from 'chimee';
  import flv from 'chimee-kernel-flv';
  import hls from 'chimee-kernel-hls';
  import ChimeeMobilePlayer from 'chimee-mobile-player';
  export default{
    data(){
      return {
        liveinfo:'',
        activeTab: 'tab1',
        baseUrl:this.$store.state.baseUrl,
        user:null,
        num:null,
        src:'',
        html5:false,
      }
    },
    beforeMount() {
      let url=this.$store.state.svrUrl+'getLiveInfo/'+this.$route.params.id;
      const self=this;
      axios.get(url).then(response=>{
        self.$nextTick()
          .then(() => {
           /* const chimee = new Chimee({
              wrapper: this.$refs.video,
              src: response.data.data.play_m3u8_url,
              controls: true,
              autoplay: true,
              kernels: {
                flv,
                hls
              },
            });
            chimee.play();*/
            if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
              this.html5=true;
              console.log('ios-'+'videojs');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                box: 'hls',
                muted: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();

            } else if (/(Android)/i.test(navigator.userAgent)) {
              this.html5=true;
              console.log('Android-'+'videojs');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                box: 'hls',
                muted: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();
            } else {
              self.html5=false;
              console.log('PC-'+'Chimee');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();
            };
          });
        self.liveinfo=response.data.data;
        self.user=response.data.user;
        self.num=response.data.classnum;
      }).catch();

    },

**Comment by cruelwolfking** [comment]
``<script>
  import axios from 'axios';
  import Chimee from 'chimee';
  import flv from 'chimee-kernel-flv';
  import hls from 'chimee-kernel-hls';
  import ChimeeMobilePlayer from 'chimee-mobile-player';
  export default{
    data(){
      return {
        liveinfo:'',
        activeTab: 'tab1',
        baseUrl:this.$store.state.baseUrl,
        user:null,
        num:null,
        src:'',
        html5:false,
      }
    },
    beforeMount() {
      let url=this.$store.state.svrUrl+'getLiveInfo/'+this.$route.params.id;
      const self=this;
      axios.get(url).then(response=>{
        self.$nextTick()
          .then(() => {
           /* const chimee = new Chimee({
              wrapper: this.$refs.video,
              src: response.data.data.play_m3u8_url,
              controls: true,
              autoplay: true,
              kernels: {
                flv,
                hls
              },
            });
            chimee.play();*/
            if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
              this.html5=true;
              console.log('ios-'+'videojs');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                box: 'hls',
                muted: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();

            } else if (/(Android)/i.test(navigator.userAgent)) {
              this.html5=true;
              console.log('Android-'+'videojs');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                box: 'hls',
                muted: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();
            } else {
              self.html5=false;
              console.log('PC-'+'Chimee');
              const chimee = new Chimee({
                wrapper: self.$refs.video,
                src: response.data.data.play_m3u8_url,
                controls: true,
                autoplay: true,
                kernels: {
                  flv,
                  hls
                },
              });
              chimee.play();
            };
          });
        self.liveinfo=response.data.data;
        self.user=response.data.user;
        self.num=response.data.classnum;
      }).catch();

    },

**Comment by cruelwolfking** [comment]
http://cxcy.unidoli.com/#/watchLive/22，这是观看地址。在PC没有问题，ios就没法播放了，我不知道是不是我的写法有问题，听别人说加上box：‘hls’，这个我试了也不行

**Comment by toxic-johann** [comment]
移动端播放 m3u8 box 请填写 native

**Comment by cruelwolfking** [comment]
试了，iosQQ浏览器和原生浏览器都可以播放了，然后安卓播放失败，微信播放失败

**Comment by cruelwolfking** [comment]
现在已经加上 box：‘native’了

**Comment by toxic-johann** [comment]
加个 vconsole 或者和连电脑调试一下。看看有何报错信息。

**Comment by toxic-johann** [comment]
无更多信息提供的话先暂时关闭了。

**Comment by allenYetu211** [comment]
Android微信如果是使用的x5内核， 则可以直接播放m3u8。

如果内核是chrome，则无法直接使用m3u8，但支持MES，需要进行转码处理。 

在手机上面使用flv 则成为可能。
