### ISSUE TITLE
华为手机 在微信中 全屏播放后，再退出全屏 会导致微信原生 导航栏 缺省一部分；

### ISSUE THREAD

**Issue by hehui-Js** [Chimeejs/chimee#105]
华为手机在微信里面全屏播放后，再退出全屏 会导致微信原生 导航栏 缺省一部分；

![wechatimg226](https://user-images.githubusercontent.com/20576534/37238181-dd6707f4-245b-11e8-836e-cedbce0ed9e8.jpeg)

如果 在全屏播放前，把手机底部的虚拟导航栏隐藏，全屏播放，然后再退出全屏播放就没有问题。

华为手机型号：HUAWEI MT7-TL10   
安卓版本：4.4.2
微信版本： 6.6.5 
视频链接：http://www.runoob.com/try/demo_source/movie.mp4
chimee版本：当前最新版本 （通过 npm 安装）

**Comment by toxic-johann** [comment]
使用以下链接测试一下全屏后是否有相关问题？[https://davidwalsh.name/demo/fullscreen.php](https://davidwalsh.name/demo/fullscreen.php)

**Comment by yandeqiang** [comment]
这个被浏览器接管了吧。 用的系统播放器的全屏方法吧

**Comment by hehui-Js** [comment]
恩，谢谢各位大佬。目前应该可以断定是手机系统本身的问题。用该手机播放优酷的视频也有类似的问题。

**Comment by toxic-johann** [comment]
好的。
