### ISSUE TITLE
关于播放与用户体验的意见建议：

### ISSUE THREAD

**Issue by trainliang** [Chimeejs/chimee#107]
# 关于cdn：
 _现在有一国内可用实时更新的jscdn加速，更新后就可使用，支持模糊自动更新js版本文件；_
## 地址：
https://www.jsdelivr.com/
## pc-player地址示例：
https://cdn.jsdelivr.net/npm/chimee-player@1.3.3/lib/chimee-player.browser.min.js
## mobile=player地址示例：
https://cdn.jsdelivr.net/npm/chimee-mobile-player@0.1.4/lib/chimee-mobile-player.browser.min.js
# 关于资源弱网加载失败：
建议优化js加载，弱网检测，加载失败检测，资源弱网检测
# 关于资源缓存下载优化：
资源80%的获取是在弱网下，而单线程下载受限于服务器传输速度，以及环境对带宽的影响，特别是墙外，下午6-11点的高峰期，资源加载失败以及缓存失败时有发生，建议支持多线下载自定义下载线程，有效优化提升缓存效率，减少等待，以及提高资源播放成功率
# 关于播放进度暂停以及刷新恢复
资源以及页面刷新是大概率操作，特别是在网络加载失败、页面断网恢复的时候，但是每次都是在资源的开始加载，用户需要再次点击播放进度才能再次恢复播放，相当影响体验以及浪费服务器下载资源
# 关于弹幕系统
希望能有一个比较好的方案，适合小型视频方案，以便更利于弹幕的存储下发实施

**Comment by toxic-johann** [comment]
多线程下载资源有所计划，可在此  issue 下补充。https://github.com/Chimeejs/chimee/issues/24

播放进度刷新恢复应该需要写一个插件在 localstorage 等地方缓存播放进度，然后在页面刷新后更改播放进度。可在此处补充 https://github.com/Chimeejs/chimee/issues/97。

**Comment by trainliang** [comment]
- （希望提高优先级）页面资源多线下载一样多线下载ts文件，而且可根据资源自定义下载线程
- cdn问题是jsdeliver已经在实时同步文件了，国内cdn节点，而且支持版本锁定，希望可以做出公示
