### ISSUE TITLE
播放到视频结束，点击进度条将进度置于某一进度上，再点击播放，出现range计算错误

### ISSUE THREAD

**Issue by leonardoFu** [Chimeejs/chimee#108]
如图:
bug1：点击播放后拖拽进度条出现报错
![bug1](http://image-leo.test.upcdn.net/images/chimeeBug1.jpg)

bug2: 播放结束，播放器暂停时seek到视频开始，点击播放，range计算似乎有点问题
![bug2](http://image-leo.test.upcdn.net/images/chimeeBug2.jpg)

**Comment by toxic-johann** [comment]
相关的 chimee version提供下，似乎用的是旧版本。

可通过 chimee 实例直接查看。

```
chimee.version
```

**Comment by leonardoFu** [comment]
这个是在官网上的示例发现的，我安装一个新版本看一下能不能重现
