### ISSUE TITLE
chimee 对于直播配置自动审核

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#11]
[关联 issue ](https://github.com/Chimeejs/chimee-kernel-flv/issues/2)

**Comment by huzunjie** [comment]
关联issue里kernel里自动play建议提到chimee，综合插件状态和autoplay配置一起判断 ---- 避免下面两个可能出现的问题：

1.  用户配置达不到预期 --- 设置了非自动播放但是依然自动播放了
2. 直播要增加片头广告的场景，kernel内部对插件状态无感知，可能出现广告和内容同时播放的问题

**Comment by toxic-johann** [comment]
交由[#15](https://github.com/Chimeejs/chimee/issues/15) 梳理
