### ISSUE TITLE
增加配置屏蔽默认video右键

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#112]
如题，场景：
如果没有插件层，或者插件层直接pointer-events none时，右键事件直接穿透到video上，导致会出现诸如"显示控制条"等原生右键菜单，建议增加配置对video标签默认绑定contextmenu事件

**Comment by toxic-johann** [comment]
已在 [0.10.1](https://github.com/Chimeejs/chimee/releases/tag/0.10.1) 中增加该选项。具体文档可参考 https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/api/chimee-api.md#nodefaultcontextmenuv0101-%E5%90%8E
