### ISSUE TITLE
页面嵌套在 iframe 中全屏时，需要设置 allowfullscreen 属性

### ISSUE THREAD

**Issue by yandeqiang** [Chimeejs/chimee#113]
如题。 否则会使用样式全屏，还得手动将 ifame 全屏。
参考： https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled

**Comment by toxic-johann** [comment]
https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha.4  可设置样式全屏的方法。
