### ISSUE TITLE
支持在线解密对称加密流

### ISSUE THREAD

**Issue by wz3321653** [Chimeejs/chimee#114]
![_20180427161625](https://user-images.githubusercontent.com/38780868/39352161-726c7208-4a36-11e8-835e-e179c93dd8a5.png)
![_20180427161631](https://user-images.githubusercontent.com/38780868/39352162-72ba820e-4a36-11e8-9146-d64f1bfbdd4c.png)

流地址：
http://vtest.96koo.net/common/LzEvcmVsZWFzZS8yMDE3MTIyMS9aaXBhZFhpSzhQL1ppcGFkWGlLOFBfNjQwXzgwMA==_499.m3u8
播放VOD-HLS时，卡在key位置一直无法播放。

**Comment by songguangyu** [comment]
@wz3321653 我今天又仔细看了 http://vtest.96koo.net/common/LzEvcmVsZWFzZS8yMDE3MTIyMS9aaXBhZFhpSzhQL1ppcGFkWGlLOFBfNjQwXzgwMA==.key 你这个KEY请求不支持跨域

**Comment by wz3321653** [comment]
@songguangyu 
你好 key已支持跨域，但是仍然无法播放

**Comment by songguangyu** [comment]
目前hls 支持通用的加密模式
