### ISSUE TITLE
webpack打包之后的文件达到600+k，是不是太大了？

### ISSUE THREAD

**Issue by kabulore** [Chimeejs/chimee#118]
Hello !

只引用了这俩
`import Chimee from 'chimee';
import hls from 'chimee-kernel-hls';`

打包完之后看了一下，两个module 里面都引用了lib/index.browser.js，但是这俩文件却不完全一样，最终这俩文件压缩完也占据了300多k，这有什么解决办法么？

**Comment by toxic-johann** [comment]
chimee-kernel-hls 引用了 hls.js ，这个库本来体积就比较大。。

chimee 在之后会做相关的优化。

**Comment by toxic-johann** [comment]
另外如果使用的 webpack 打包的话，请不要直接应用 lib/index.browser.js。该包是全部打包的版本，直接在线上使用的。如果使用webpack 打包的话，请使用 index.js 或者 index.mjs 版本。这两个版本可以通过 webpack 的 tree shaking 等功能节省代码体积。

**Comment by kabulore** [comment]
@toxic-johann  并没有直接引用，而打包的时候就自动把index.browser.js打进来了，是需要做一些配置么？我用的 webpack 4.6

**Comment by toxic-johann** [comment]
你看看是不是 webpack resolve 的 mainfeilds 设置错误。 https://webpack.js.org/configuration/resolve/#resolve-mainfields

如果使用了 browser 在第一位，会优先引入 browser。

如果有其他插件干扰，不好改这个。可以加个 alias 到 index.mjs 或者 index.js

**Comment by kabulore** [comment]
@toxic-johann 好的，十分感谢！

**Comment by shen-lan** [comment]
vue-cli 3.0 打包后发现默认打包的是 index.browser ，所以体积很大。
并不是index.min.js
怎么处理？

**Comment by toxic-johann** [comment]
能配置 alias 吗？
