### ISSUE TITLE
在部分浏览器中 m3u8 文件转码的 blod地址有问题，导致无法播放

### ISSUE THREAD

**Issue by falost** [Chimeejs/chimee#120]
在部分浏览器当中，视频源地址为m3u8格式的文件，会造成 blod的文件地址中的 **:**  被编码 ，导致浏览器加载失败，无法正常播放
![tim 20180515163210](https://user-images.githubusercontent.com/13709107/40045825-e984a448-585d-11e8-8348-4d8c355ac25d.png)

目测测试出的浏览器为 **2345浏览器**和**搜狗浏览器**

并且IE10以下 chimee-kernel-hls 好像不能工作了

**Comment by toxic-johann** [comment]
hls.js 自身不兼容 IE10 及以下浏览器。 https://github.com/video-dev/hls.js#compatibility

故 chimee-kernel-hls 在 IE10 及以下浏览器不能工作。
