### ISSUE TITLE
清晰度切换的时候，时长会增加duration所设置的值 导致跳屏

### ISSUE THREAD

**Issue by falost** [Chimeejs/chimee#121]
如果设置了 duration  的话，视频处于播放状态 ，并且 immediate: false，那么会等待视频播放到 当前播放位置 + duration 的值之后，才会执行切换，如果视频处于暂停状态时进行切换，并且 immediate: false, 那么视频位置并不能改变，也就无法完成 切换了

但是如果设置 immediate: true的话，视频会立即切换到 当前视频播放位置 + duration 的值 并继续播放， 并且暂停状态切换也会直接切换， 但是就会造成视频跳屏播放了，会卡掉几秒， 如果多来几次 ，视频就跳转 就会一直累加 duration  的值 当播放的时候，就会跳的更多了
 @toxic-johann

**Comment by toxic-johann** [comment]
最新版已修复问题 https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha.8

请使用如下指令下载。

```
npm install chimee@next
```

**Comment by falost** [comment]
非常感谢 已经解决了
