### ISSUE TITLE
使用PC端 Chimee-Player解决方案 ，视频加载前、切换时间，loading不出现

### ISSUE THREAD

**Issue by allenYetu211** [Chimeejs/chimee#124]
视频加载前loading 不出现，  怀疑 chimee 没有检测到视频加载的load。

使用chimee-player 版本： "chimee-player": "^1.4.3"

浏览器： Chrome 66.0.3359.181

操作系统： MacOS 10.12.6

在文档种没有查到控制loading， 只找到了手机端解决方案的一个preload, 但也是没有效果，请问

代码
```js
__play = new ChimeePlayer({
            wrapper: '#wrapper',
            src: xxx.mp4,
            isLive: false,
            box: 'native',
            autoplay: true,
            controls: true
        });
```

**Comment by toxic-johann** [comment]
@yandeqiang 关注一下

**Comment by yandeqiang** [comment]
视频加载前、切换时间， 不是很懂什么意思。 
按照你的配置， `autoplay: true` 的话， 初始化就会直接加载的， 应该来不及切换时间吧。
再描述一下吧。

**Comment by allenYetu211** [comment]
@yandeqiang   
设置自动播放时： 资源开始下载，由于网速问题下载速度较慢时， 预期出现 loading「现象：未出现」
点击进度条某个时间点：  重新开始获取数据，预期出现loading「现象：未出现」

**Comment by yandeqiang** [comment]
我这试了是可以的出现 loading 的
不过这块还有个逻辑是，暂停的时候不显示 loading 的， 是因为这个问题吗？

**Comment by allenYetu211** [comment]
@yandeqiang   目前不是这个问题，这给地方下周三我会弄一个测试地址，到时候我会留下一个地址，还得麻烦看看具体表现。
「目前由于本地做了一些调整，直接上测试环境会影响到其他人工作，下周二前会解决这个问题。」

**Comment by allenYetu211** [comment]
@yandeqiang 感谢持续关注这个问题。

**Comment by toxic-johann** [comment]
现在这个问题进展如何？

**Comment by allenYetu211** [comment]
不好意思， 由于优先级的问题，在处理其他问题，今天我会将这个发版一次。
