### ISSUE TITLE
封面图设置总无效是怎么回事？

### ISSUE THREAD

**Issue by hanlinzhe** [Chimeejs/chimee#125]
player.poster 设置总是无效，直接显示视频第一帧了

**Comment by toxic-johann** [comment]
设置方式是？请问有复现环境吗？

使用该 demo 暂时不能复现。 https://github.com/Chimeejs/chimee/tree/next/demo/poster

**Comment by hanlinzhe** [comment]
直接设置了player 的poster 属性。另外，视频时长初始化时总获取不到

**Comment by toxic-johann** [comment]
提供一下复现环境，不然无法定位问题。
