### ISSUE TITLE
关于播放器初始化时工具栏总时长显示为0:00 播放器依然能播放问题

### ISSUE THREAD

**Issue by dely-yuan** [Chimeejs/chimee#127]
在window10系统中似乎没有出现，在window7中经常出现，问题出现时在控制台中打印document.querySelector('video').duration可以去到值

**Comment by toxic-johann** [comment]
提供下用的包，具体环境或者复现方法等。

**Comment by dely-yuan** [comment]
"chimee": "^0.10.0-alpha.9",
"chimee-helper": "^0.2.11",
"chimee-kernel-hls": "^1.3.0",

**Comment by yandeqiang** [comment]
监听 durationchange 事件，看看， 是否可以触发这个事件.

**Comment by dely-yuan** [comment]
问题播放器不会触发

**Comment by toxic-johann** [comment]
durationchange 该事件会触发的。问题描述不是很清晰。请提供更多信息来表达你想反馈的问题。
