### ISSUE TITLE
穿透插件不绑定事件时不会触发video上的事件

### ISSUE THREAD

**Issue by joenil** [Chimeejs/chimee#128]
问题描述：`chimee-plugin-controlbar`插件里绑定了`click`事件控制视频播放/暂停，自定义穿透事件不设置`events`中对应的`click`事件时，不触发video上的`click`事件，`0.9.5`版本无此问题。
chimee版本：0.10.0-alpha.9
chimee-plugin-controlbar版本：0.4.4
问题重现demo：[https://codesandbox.io/s/9j880ynnrr](url)

插件声明：
``` javascript
export default {
  name: "myPlugin",
  penetrate: true,
  el: '<div class="my-plugin"><div class="my-plugin-inner"></div></div>',
  create() {}
};
```

初始化：
``` javascript
new Chimee({
  plugin: [
    ChimeePluginControlbar.name, 
    MyPlugin.name
  ]
}
```

**Comment by toxic-johann** [comment]
已修复，下载[0.10.0-alpha.10](https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha.10) 即可。

可使用如下命令反馈

```
npm install chimee@next
```

感谢反馈。
