### ISSUE TITLE
播放器播放崩溃，控制台报错

### ISSUE THREAD

**Issue by dely-yuan** [Chimeejs/chimee#129]
初始加载为标清地址，在切换到高清地址后，频繁更改播放进度，控制台报错，画面黑屏，播放进度回到0：00 再点击播放无反应
## Expected Behavior【期望行为】

播放器切换到高清后，更改播放进度正常
## Current Behavior【实际表现】

播放器切换到高清后，更改播放进度时，播放器崩溃
## Steps to Reproduce【复现方法】

1.标清地址 http://v.96koo.net/common/LzEvcmVsZWFzZS8yMDE4MDUzMC9NQmoycnhITUUzL01CajJyeEhNRTNfNjQwXzgwMA==_8446.m3u8
2.高清地址
http://v.96koo.net/common/LzEvcmVsZWFzZS8yMDE4MDUzMC9NQmoycnhITUUzL01CajJyeEhNRTNfOTYwXzEwMDA=_8446.m3u8
3.
4.

## Environment 【相关环境】

"chimee": "^0.10.0-alpha.9",
    "chimee-helper": "^0.2.11",
    "chimee-kernel-hls": "^1.3.0",
    "chimee-plugin-popup": "0.0.7",
window10系统
各大浏览器

![s_5 d 7q0sa16w1hotoz dj](https://user-images.githubusercontent.com/39255943/40772971-0f3faee2-64f4-11e8-8b51-683936bd160f.png)

**Comment by toxic-johann** [comment]
直接使用高清流进行播放，设置是否会出现问题？感觉像是流解释的问题。

**Comment by 594904020** [comment]
我做了一个视频的列表，滚动后报了一个异常：
![image](https://user-images.githubusercontent.com/32348909/40792202-eeb17506-652b-11e8-8b0e-85a51227ba75.png)

**Comment by 594904020** [comment]
好的。谢谢

**Comment by toxic-johann** [comment]
@594904020 你这个应该不是这个 issue 的问题吧。。你单独提一个 issue 吧

**Comment by toxic-johann** [comment]
@dely-yuan mac chrome 暂时无法复现。我明天找台 windows 试试。

**Comment by toxic-johann** [comment]
感觉应该是 seek 的时候出现了错误。你可以 debug 看看有没有更多错误资料。

**Comment by dely-yuan** [comment]
怎么debug

**Comment by dely-yuan** [comment]
在什么节点debug

**Comment by yandeqiang** [comment]
暂时定位到 duration = NaN 的错误
