### ISSUE TITLE
初始化时未传入src属性报错

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#13]
代码大概如下：
```javascript
this.player = new Chimee({
    width: this.width,
    height: this.height,
    wrapper: this.$refs.player,
    isLive: this.isLive,
    autoplay: true,
    controls: true
});
```
此时只是想初始化播放器，后续通过load方法载入视频，但是目前会直接报`video player is not already, must init player`

debug了一下代码发现在播放器初始化的时候会自动去加载src内容，此时src为空，走入后面逻辑

**Comment by toxic-johann** [comment]
将 autoload 设置为 false 试试？

提示不够人性化嗷。。

**Comment by skyline0705** [comment]
一样，这块逻辑看了下跟autoplay无关，是只要初始化传入没有src就会报错。

**Comment by toxic-johann** [comment]
不是 autoplay 是 autoload

**Comment by toxic-johann** [comment]
查看文档的[ autoload 部分](https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#video属性)。

相应规则见下图。

![](https://ws1.sinaimg.cn/large/006tNc79gy1flbq6dh5edj30pm05rab8.jpg)

**Comment by skyline0705** [comment]
autoload目前未做设置，仍然报此错误

**Comment by toxic-johann** [comment]
默认是 true，所以如果你没有 src 的话要把它关掉。

**Comment by skyline0705** [comment]
了解了…
不过这块是否有可能默认根据是否videoConfig上有src来判断呢？

**Comment by toxic-johann** [comment]
可以的。不过记得当时是有点难做。（主要自己的代码问题）。我们内部规划下。

**Comment by skyline0705** [comment]
感谢感谢~~

**Comment by toxic-johann** [comment]
已在 [0.4.2](https://github.com/Chimeejs/chimee/releases/tag/0.4.2) 修复
