### ISSUE TITLE
实例上的ready promise resolve时执行play方法，不会触发play事件

### ISSUE THREAD

**Issue by joenil** [Chimeejs/chimee#132]
实例上的ready promise resolve时执行play方法，不会触发插件里的play事件

## Expected Behavior【期望行为】
应该触发插件里的play事件

## Current Behavior【实际表现】
不触发插件里的play事件

## Steps to Reproduce【复现方法】
https://codesandbox.io/s/p70orjnnr0

**Comment by toxic-johann** [comment]
![image](https://user-images.githubusercontent.com/2577157/41494956-12155470-714f-11e8-98bb-0d351227b921.png)

浏览器做了限制，可以查看这个地址 https://goo.gl/xX8pDD
