### ISSUE TITLE
play和volumechange等事件不触发的一些诡异问题

### ISSUE THREAD

**Issue by joenil** [Chimeejs/chimee#133]
在实例上监听play和volumechange等事件，对播放器执行相关操作后，不触发事件

## Expected Behavior【期望行为】

只要在实例上监听了事件，在播放器收到某个操作后，都应该触发该事件

## Current Behavior【实际表现】

事件不触发，可以看到控制条上的播放按钮还是“待播放”状态，音量条还是有音量。

## Steps to Reproduce【复现方法】
https://codesandbox.io/s/p70orjnnr0

``` javascript
import chimee from "chimee";
import controlbar from "chimee-plugin-controlbar";

const plugin = {
  name: 'plugin',
  events: {
    play () {
      console.log('plugin play')
    }
  }
}

chimee.install(plugin)

const player = new chimee({
  wrapper: "#app",
  autoplay: false,
  controls: true,
  src: "http://cdn.toxicjohann.com/lostStar.mp4",
  plugin: [plugin.name]
});

player.on('play', e => {
  console.log('play1')
})

player.$video.addEventListener('play', e => {
  console.log('play2')
})

player.play()
```

**Comment by joenil** [comment]
可能会触发chrome的自动播放限制，但在实际情况中可能用户MEI比较高（https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei）还是可以自动播放，所以在查看问题复现时请把“自动播放播放策略”关掉。

**Comment by joenil** [comment]
可以看下是不是因为绑定事件时和操作播放器时的video不是同一个node节点引起的。

**Comment by yandeqiang** [comment]
可能是实例化是异步操作。 你直接写在下面的话， 可能没有起到作用。插件还没有完成 inited ，事件收不到。

**Comment by toxic-johann** [comment]
主动 play 并没有触发 play 事件

**Comment by toxic-johann** [comment]
已定位问题，第一次 load 触发 switchKernel 。同时进行 play 的话会造成事件传递缺失。

**Comment by toxic-johann** [comment]
在 [0.10.2](https://github.com/Chimeejs/chimee/releases/tag/0.10.2) 中修复
