### ISSUE TITLE
使用load重新加载视频后调用play方法不触发事件

### ISSUE THREAD

**Issue by joenil** [Chimeejs/chimee#136]
使用load重新加载视频后调用play方法不触发事件

## Expected Behavior【期望行为】
应该触发play事件，控制条的播放按钮状态改变

## Current Behavior【实际表现】
没有触发play事件，控制条的播放按钮还是待播放

## Steps to Reproduce【复现方法】
https://codesandbox.io/s/54yp87160k
``` javascript
parent.load({
     src: parent.src,
     box: parent.box,
     kernels: parent.kernels
})
.then(() => {
     parent.play();
});
```

## Environment 【相关环境】
chimee: 0.10.3
controlbar: 0.4.4

**Comment by toxic-johann** [comment]
问题应该在此段 https://github.com/Chimeejs/chimee/blob/master/src/dispatcher/index.js#L477-L483

**Comment by toxic-johann** [comment]
[0.10.4](https://github.com/Chimeejs/chimee/releases/tag/0.10.4) 中修复
