### ISSUE TITLE
如何做播放统计

### ISSUE THREAD

**Issue by falstack** [Chimeejs/chimee#138]
## Expected Behavior【期望行为】
当视频第一次开始播放的时候，要做播放统计，该如何实现

## Current Behavior【实际表现】
在 chimeePluginControlbar 的 play 按钮的 config 里加了 event: { click }，但是无效，并且理论上统计不应该绑定在这里

## Possible Solution 【可选方案】
引入了 statePlugin，想通过这个插件来配置监听 playing 事件，然后 emit 一个事件出去，但是没有 demo 不知道怎么写，也不知道是否能够实现

## Steps to Reproduce【复现方法】
none

## Environment 【相关环境】
PC web
使用了 chimee play，引入和 chimeePluginControlbar  和 chimeePluginCenterState

**Comment by yandeqiang** [comment]
优先使用 https://github.com/Chimeejs/chimee-plugin-log 来做日志打点，具体配置可以参考文档
其次在 chimeePluginControlbar 中配置，可以对点击事件进行监控，却是不应该写在这块，除非做点击打点
```js

            play: {
              // bitmap: true,
              event: {
                click() {
                  console.log('emit')
                }
              }
            }
``` 
也是可以实现的

**Comment by toxic-johann** [comment]
按照文档使用 `$on` 监听即可 https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/api/chimee-api.md#on

**Comment by falstack** [comment]
谢谢，我待会试试
