### ISSUE TITLE
关于isLive的参数配置

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#14]
目前isLive的的选项除了在controller-plugin中看到使用外，地方并无看到使用，而且此处又与plugin中细粒度控制图标展示与否冲突，有一定的歧义性，希望对于此参数做进一步考虑

**Comment by skyline0705** [comment]
抱歉刚看到在自动播放上还有使用，综合考虑，isLive的歧义性较多，还是希望对此参数能有一个相对明确的定义，配置一般是作为组件层级的使用，但是目前isLive看起来更接近于业务层级的配置，而不同的业务场景下对isLive的定义其实或多或少都有自己的定义

**Comment by toxic-johann** [comment]
isLive 主要用于标记是否是直播，在 kernel 层处理会有所区别。

另外其他表层插件会根据是否是直播做不同区别的展示。

**Comment by skyline0705** [comment]
我觉得还是需要明确一下isLive的定义，目前isLive直接跟autoplay设置冲突，设置isLive之后autoplay参数直接默认为true，这块很容易造成使用歧义性

**Comment by toxic-johann** [comment]
关于表现层的行为这是因为当时设置皮肤综合考虑了点播和直播的情况。

这一块 @yandeqiang 关注下。

**Comment by yandeqiang** [comment]
目前表现层，如控制条， 拿 isLive 这个参数， 是为了给一个默认图标组合而已，如果，你自己有对图标的组合有做具体的设置，则采用用户的设置。可以看下。https://github.com/Chimeejs/chimee-plugin-controlbar/blob/master/README.md#组件相关问题
