### ISSUE TITLE
使用seek方法或chimee 上直接设置 currentTime，不能实现定位到上次播放时间位置

### ISSUE THREAD

**Issue by westdrug** [Chimeejs/chimee#140]
使用seek方法或chimee 上直接设置 currentTime， 猜想设置是成功的，可能在某个异步操作中又被重置为0了。直接操作 原生 video，是可以的。感觉不严谨。
也报了很人性化的警告：

> You are trying to obtain video, we will return you the DOM node. It's not a good idea to handle this by yourself. If you have some requirement, you can tell use

**Comment by toxic-johann** [comment]
用的什么版本？
遇到的什么问题？
需要怎么样解决？
按照 issue 模版描述一下
