### ISSUE TITLE
browser throw error when import Chimee with esm file

### ISSUE THREAD

**Issue by lizheming** [Chimeejs/chimee#142]
使用 ES Module 方式引入 Chimee 编译的 esm 包报错。
Browser throw error when we import Chimee esm build file with es module type.

## Expected Behavior【期望行为】

Import normal.

## Current Behavior【实际表现】

![image](https://user-images.githubusercontent.com/424491/43708795-da4678ae-999d-11e8-9a47-3d3c5cc6c37c.png)

> Uncaught TypeError: Failed to resolve module specifier "babel-runtime/helpers/typeof". Relative references must start with either "/", "./", or "../".

## Steps to Reproduce【复现方法】

demo page: https://imnerd.org/lab/chimee/

**Comment by lizheming** [comment]
那 index.mjs 是用来做什么的呢？ for node ？

**Comment by toxic-johann** [comment]
嗯嗯

**Comment by lizheming** [comment]
但是 Chimee 并不支持 node 端吧？

**Comment by toxic-johann** [comment]
主要用于 webpack/rollup 二次编译。

**Comment by lizheming** [comment]
如果是这样的话是否有必要把它上传到仓库中来维护呢？
