### ISSUE TITLE
在安卓、IOS系统的微信/Safari浏览器中，不全屏无法播放声音

### ISSUE THREAD

**Issue by dutong0321** [Chimeejs/chimee#143]
## Expected Behavior【期望行为】
在安卓、IOS系统的微信/Safari浏览器中，不全屏也可以播放声音。

## Current Behavior【实际表现】
在安卓和IOS系统的微信/Safari浏览器中，不全屏无法播放声音，而且IOS系统的微信和Safari浏览器全屏也无法播放声音。

**Comment by toxic-johann** [comment]
提供复现环境，以及更多相关资料。

例如使用的是什么库。

并且检查 muted 属性的设置。

**Comment by dutong0321** [comment]
非常感谢，的确是因为我的个人原因造成muted属性设置错误，再次拜谢！
