### ISSUE TITLE
IE 11 无法播放 已添加polyfill  错误提示「Unhandled promise rejection TypeError: 对象不支持此操作」

### ISSUE THREAD

**Issue by allenYetu211** [Chimeejs/chimee#148]
## Expected Behavior【期望行为】

正常播放

## Current Behavior【实际表现】

无法播放并提示 「Unhandled promise rejection TypeError: 对象不支持此操作」

## Steps to Reproduce【复现方法】

初始播放器后报错

## Environment 【相关环境】

window 10
IE 11

## 错误信息

![18ad81fa042ba05fea8ab588a8931564](https://user-images.githubusercontent.com/17957079/46790657-034ace00-cd72-11e8-81de-5ab536a8594e.png)

**Comment by allenYetu211** [comment]
@welefen @skyline0705 @toxic-johann @huzunjie

**Comment by allenYetu211** [comment]
在chimee.org 放入直播波流地址，同样错报。  官网所指的IE支持是指edge？
![image](https://user-images.githubusercontent.com/17957079/46791677-3a21e380-cd74-11e8-814f-d1383a8bad14.png)

**Comment by allenYetu211** [comment]
我是使用的 chimee-player

**Comment by skyline0705** [comment]
直播的话，的确无法支持IE11，IE11下面部分是不支持MediaSource的，以及完全不支持fetch……
你的环境是win10，所以目测应该是fetch不支持导致的报错。kernel部分依赖fetch的读取二进制的能力。除非你能够换成ws之类的进行传输

**Comment by allenYetu211** [comment]
💯  我看那上面写着支持IE ，让我觉得这个是可以执行的。

明天提测，我感觉我会失业。
