### ISSUE TITLE
是否应该将 box, kernels 支持度提升到 chimee 层。

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#15]
现阶段判断 box， kernels 的职责其实一直都是 kernels 层负责。

是否有必要提升到 chimee 层做统一负责？、

@huzunjie @332065255 @songguangyu @yandeqiang

**Comment by huzunjie** [comment]
需要统一梳理一下现有kernels内有涉及到video状态操作的地方，如果不经过chimee统一进行状态管理，后面必然会导致插件开发过程中出现状态的问题，所以得考虑提升到chimee或者kernel提供相应的方法或钩子给chimee。

**Comment by songguangyu** [comment]
OK 今天看一下这个问题。
