### ISSUE TITLE
在ie8设置视频初始时间，报错

### ISSUE THREAD

**Issue by hjx5309** [Chimeejs/chimee#151]
## Expected Behavior【期望行为】

不报错，可以正常设置视频的初始时间
## Current Behavior【实际表现】

      var vie = new Chimee ({
        wrapper: '#wrapper',
        src: 'http://cdn.toxicjohann.com/lostStar.mp4',
        controls: true,
        autoplay: false
      });
      vie.currentTime = 60;
控制台报 DOM Exception: INVALID_STATE_ERR (11)
**我发现可能是因为视频未加载完成前，设置初始时间造成的，是否有加载完成后，才去设置初始时间的回调方法**

谷歌没有报这个错
## Possible Solution 
【可选方案】

## Steps to Reproduce【复现方法】

1.
2.
3.
4.

**Comment by toxic-johann** [comment]
chimee 不支持 IE8
