### ISSUE TITLE
没有画质切换吗

### ISSUE THREAD

**Issue by Adgeros** [Chimeejs/chimee#16]
画质切换是可以自己扩展插件的吗

**Comment by toxic-johann** [comment]
我们使用 [silentload](https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#-silentload) 接口进行画质切换的。

不知道能不能满足需求呢？

**Comment by Adgeros** [comment]
@toxic-johann 可以，那切换按钮呢

**Comment by toxic-johann** [comment]
你指 ui 按钮吗？你是用的我们的皮肤吗? @yandeqiang 看看

**Comment by yandeqiang** [comment]
@Adgeros 可以看看， chimee-plugin-controlbar 插件，自带切换清晰度插件， 还可以扩展自定义插件。具体可以看看 https://github.com/chimeejs/chimee-plugin-controlbar

**Comment by toxic-johann** [comment]
@Adgeros 还有不明白的地方吗？
