### ISSUE TITLE
苹果产品网页的自动播放问题

### ISSUE THREAD

**Issue by closertb** [Chimeejs/chimee#17]
这个苹果产品的自动播放问题，貌似还是黑洞？？？这个产品能解决吗？

**Comment by toxic-johann** [comment]
额。不能。

不过 iOS 下如果视频是静音的话，是允许自动播放的，设置 mute 属性为 true 即可。

如果是 iOS 下的微信场景，可以[调用微信的 jssdk 解决问题](https://www.w3ctech.com/topic/1165)。
