### ISSUE TITLE
切换清晰度后流加载失败有重复createElement('video')的问题

### ISSUE THREAD

**Issue by huzunjie** [Chimeejs/chimee#19]
模拟了一下“slow 3G”网络，发现一次切换清晰度操作有createElement('video')多次，需要排查失败重试逻辑是不是有没走到destroy的情况。

**Comment by toxic-johann** [comment]
补充图片资料，复现平台 windows

![](https://ws3.sinaimg.cn/large/006tNc79gy1fld0g8gl8vj31e90wl1kx.jpg)

![](https://ws3.sinaimg.cn/large/006tNc79gy1fld0h4nppej30jk07imxf.jpg)

![](https://ws3.sinaimg.cn/large/006tNc79gy1fld0haq7h3j30j80b13z0.jpg)

![](https://ws4.sinaimg.cn/large/006tNc79gy1fld0hjcj3zj30ko0mr405.jpg)

![](https://ws4.sinaimg.cn/large/006tNc79gy1fld0hoeji5j30fj0act8z.jpg)

**Comment by toxic-johann** [comment]
可能与 [#5](https://github.com/Chimeejs/chimee/issues/5) 有关联。

**Comment by huzunjie** [comment]
通过 http://gyblog.cn/static/html/index_hls.html 拿纯解码层调试看，基本确定与神秘的#5 ended事件无关了；上述问题留意相应场景有没有应该销毁但未销毁的对象就好了。

**Comment by toxic-johann** [comment]
好的

**Comment by toxic-johann** [comment]
@huzunjie 具体的 remove 代码是在哪里打的？并没有看到。

Mac 上可能复现这个问题吗。。我现在本地无法复现。

**Comment by huzunjie** [comment]
具体remove是在 chimee/dom.js 的 removeVideo 方法里打的。

因为我试验时改了 createElement('video') 那里的逻辑，直接打到DOM树里，跟你原有逻辑还是有差别。

**Comment by toxic-johann** [comment]
嗯。。。我之前尝试了一下。还是没有复现。

**Comment by huzunjie** [comment]
重试逻辑中的正常现象
