### ISSUE TITLE
封面在微信中无效 而且整个播放器的大小和图片是宽高是一样的

### ISSUE THREAD

**Issue by Chenzexinnizheshuai** [Chimeejs/chimee#210]
希望在手机端显示封面图片，浏览器中使用是可以成功的，但是在微信中却无效，而且整个播放器在未播放状态的情况下，整个播放器的宽高和图片的宽高是一样的，但是图片不显示

<template>
    <div>
        <div id="wrapper">
            <container>
                <video></video>
            </container>
        </div>
    </div>
</template>

<script>
import ChimeeMobilePlayer from 'chimee-mobile-player';
import  'chimee-mobile-player/lib/chimee-mobile-player.browser.css';
import img from './logo.png'
export default{
    async mounted(){
        new ChimeeMobilePlayer({
        wrapper: '#wrapper',  // video dom容器
        src: 'http://cdn.toxicjohann.com/lostStar.mp4',
        autoplay: true,
        controls: true,
        playsInline: true,
        preload: 'auto',
        x5VideoPlayerFullscreen: true,
        x5VideoOrientation: 'landscape|portrait',
        xWebkitAirplay: true,
        muted: false,
        poster:img,
        // removeInnerPlugins: ['chimeeMobiControlbar', 'chimeeState'] // 需要移除的插件
        });
    }
}
</script>

**Comment by razor1895** [comment]
chimee-mobile-player.browser.css  这个文件里面你把 container 的 display: block 属性给去掉就行了

**Comment by Chenzexinnizheshuai** [comment]
还是不行啊 呜呜呜。。

**Comment by Chenzexinnizheshuai** [comment]
浏览器就没问题

**Comment by razor1895** [comment]
```css
container,
video {
    display: block;
    width: 100%;
    height: 100%;
    background: #000;
    outline: none;
}
```

我是把这里的display: block去掉就好了

**Comment by Chenzexinnizheshuai** [comment]
我也给去掉了  但是还是不行呀   在微信上还是有问题  浏览器就没问题

**Comment by Chenzexinnizheshuai** [comment]
而且我在微信上  封面图片都不展示

**Comment by razor1895** [comment]
```css
container {
  display: flex;
}
```

这样

**Comment by Chenzexinnizheshuai** [comment]
还是不行呀  呜呜呜

**Comment by Chenzexinnizheshuai** [comment]
问大佬个问题   播放器在h5上没有调节音量的控制器，怎么解决啊  不太会用这个播放器

**Comment by razor1895** [comment]
这个没有音量控制的...  你要做的话得二次开发一下，video 标签有个volume属性可以控制音量 或者你换video.js

**Comment by toxic-johann** [comment]
移动端目前没有做音量控制，因为一般都是使用手机原生的控制。或者手动设置 volume
