### ISSUE TITLE
预加载方案 ROADMAP

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#24]
预加载方案构思

- [ ] 多个视频之间的预加载
做法：增加一个隐藏 video 加载流，需要的时候直接切换即可。

- [ ] cacheStorage 配合 PWA 完成
做法，利用 cacheStorage 存储片段，拦截请求返回。注意判断 storage 的限制

- [ ] localStorage 或 indexedDB 读取
这个可能要修改一下各个 kernel 的设置，另外限制比较大。和光宇衡量。

**Comment by songguangyu** [comment]
初定使用 IndexedDB 进行预加载策略，后续着手进行开发。

**Comment by songguangyu** [comment]
先做一下性能测试，看一下可行性。

**Comment by toxic-johann** [comment]
indexeddb 的支持性不太好。。。要留意一下
