### ISSUE TITLE
demo页的VOD_HLS和LIVE_HLS在ios中微信和QQ里均无法播放,而在PC上正常

### ISSUE THREAD

**Issue by amhoho** [Chimeejs/chimee#261]
页面 http://chimee.org/#demo 在ios中微信和QQ里均无法播放,而在PC上正常,
更换box为native也没有用,一直显示loading,无法正常播放
已排除流地址问题,用的是正常在推流.

**Comment by toxic-johann** [comment]
如何排除流地址问题的？

**Comment by amhoho** [comment]
@toxic-johann 在推流啊 且其余播放器均正常

**Comment by toxic-johann** [comment]
其余播放器是什么？native 使用原生 video。你可以直接用 video 标签测试。

**Comment by amhoho** [comment]
@toxic-johann 我说下测试流程吧.
设备:iphone 6/6s/ipad
页面:http://chimee.org/#demo
1.在pc上chrome可正常播放vod_hls,及live_hls填写个正常的m3u8直播流后.
测试结果:正常播放.
2.在iphone 6/6s/ipad的微信/QQ中按1步骤.
测试结果:vod_hls,及live_hls均无法播放,容器更换为native也无法播放

排除流:
在ffplay中正常播放
在hls.js中正常播放
在pc的chimee也正常播放

**Comment by toxic-johann** [comment]
直接使用代码测试吧。demo页主要还是 pc 用。
