### ISSUE TITLE
chimee-kernel-flv内部未实现destroy方法，导致调用instance实例的destroy时报异常

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#27]
当使用直接播放器实例load其他直播流的时候一直不成功，所以参考官网每次rebuild的方式，发现destroy的时候走到chimee-kernel-flv内部时this.transmuxer对象不存在，于是destroy失败，关于前面的load不成功的原因我有空再排查一下看看是否需要提issue

**Comment by songguangyu** [comment]
已解决
