### ISSUE TITLE
ios无法播放hls直播

### ISSUE THREAD

**Issue by 1055041142** [Chimeejs/chimee#278]
## Expected Behavior【期望行为】

ios 安卓都能正常使用
## Current Behavior【实际表现】

ios无法播放，安卓可以

代码：
 ChimeePlayer.install(chimeePluginControlbar);
 this.videoPlayer = new ChimeePlayer({
        wrapper:"#player-con",
        src:this.url,
        isLive:true,
        // box:'hls',  //    pc浏览器播放内核  ps:  pc端必须有此属性，移动端不能有此属性
        kernels: {
          hls: ChimeeKernelHls,
        },
        poster:require('../../assets/images/live-bg.png'), 
        width:"100%",
        height:"100%",
        preload: 'auto',    
        controls: true,  
        defaultMuted: true, 
        crossOrigin: true, 
        autoplay: true,   
        playsInline: true,    
        inline: true,  
        // x5VideoPlayerType: "h5", 
        // x5VideoPlayerFullscreen: true, 
        xWebkitAirplay: true,
        x5VideoOrientation: "landscape|portrait", 
        disableUA: ['Mozilla/5.0 (Linux; Android 4.4.2; HM NOTE 1TD Build/KOT49H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.97 Mobile Safari/537.36'],
      })
## Environment 【相关环境】

import ChimeePlayer from 'chimee-mobile-player'
import ChimeeKernelHls from 'chimee-kernel-hls';
import chimeePluginControlbar from 'chimee-plugin-controlbar';

**Comment by toxic-johann** [comment]
iOS 使用 native 的播放核即可
