### ISSUE TITLE
移动端的相关事件暴露

### ISSUE THREAD

**Issue by yandeqiang** [Chimeejs/chimee#28]
1. 目前 chimee 没有暴露， touch 类的相关类的移动端事件。

2. 目前移动端， 手势比较多， 播放器，常用的三个手势，点击／拖动／滑动， 这几个手势封装在 chimee 比较好， 还是，插件自己去封装比较好？？？
我个人比较赞成封装在插件内。原因是，大部分插件的手势其实都是点击操作，只有少部分， 像 controlbar 才会有这几种手势的应用。 后期手势的扩展也是， 插件自己扩展就好了， 不然， chimee 的代码也是越来越多。

**Comment by toxic-johann** [comment]
touchstart 等尚未暴露添加即可

**Comment by toxic-johann** [comment]
touch 事件等 dom 本身有的事件已封装在 chimee 中。

至于活动拖动等事件，需要看对象。对象如果是插件本身，那当然是直接写在插件中比较好。

但是如果涉及到 video 的触摸呢？类似 click 那种争夺战。

我估计，写一个底层插件是可以满足想法的。但是我现在想不太清楚。 不如我们来理一下常见的移动端操作？

例如：

上下滑调整音量或者亮度，应该是绑定在 video 上？

拖动播放条，绑定在控制条上？

**Comment by toxic-johann** [comment]
总体来说，我感觉可以用一个穿透插件解决问题。我觉得我也可以参加下这个需求。

另外，横屏竖屏这个我估计要 chimee 提供一下。

**Comment by toxic-johann** [comment]
粗略设计，我会增加一个类似 gesture 的 penetrate 插件。里面可以按照用户要求划分为几个区域。

他们的主要职责是反馈给顶层用户操作了哪些区域，手势如何。

这当是一个便利？

其实每个插件自己写貌似都可以。但是不知道会不会混乱。感觉 @yandeqiang 可以调研一下然后反馈观感给我。

如果觉得实在太麻烦我们再讨论内置于 chimee 中的计划。

**Comment by yandeqiang** [comment]
赞同，设计一个手势插件，向上层用户反馈手势。

每个插件自己写手势的话，也是，监听 touch 事件，然后将这些事件整理后反馈给插件本身， 不直接使用 touch 事件。
可以把 监听事件／反馈手势， 剥离出来。做一个单独的插件。

**Comment by toxic-johann** [comment]
该需求交由 [chimee-plugin-gesture](https://github.com/Chimeejs/chimee-plugin-gesture) 负责。

@yandeqiang 需要的话可以找我 review。
