### ISSUE TITLE
一个页面同时开多个直播播放器，只有一个生效了

### ISSUE THREAD

**Issue by solocao** [Chimeejs/chimee#31]
要做多窗口直播，但是发现对不同id的div元素初始化chimee实例，只有一个能播放，其他的就停下来了。在点播视频，我开了两个，两个都是正常播放。是不是目前不支持多开直播？或者是多开直播占用了同一个缓冲区，导致了冲突？

**Comment by toxic-johann** [comment]
能提供一个复现现场吗？

或者相关直播流？我们确认下

**Comment by songguangyu** [comment]
确认问题，底层解码器出现了一点问题 @332065255  凌霄帮看一下

**Comment by songguangyu** [comment]
chimee-kernel-flv@1.3.6 fix it
