### ISSUE TITLE
Configuration x5VideoPlayerType should use 'h5-page' instead of 'h5'

### ISSUE THREAD

**Issue by joe223** [Chimeejs/chimee#355]
As the code show below:

https://github.com/joe223/chimee/blob/0f04e52355e9ba2316705a0982b134377f3b3729/src/config/video.ts#L246

```html
<video id="video" controls="" preload="" x5-video-player-type="h5" loop="loop" height="150" width="300">
        <source src="http://cdn.tencent.neigou.com/Public/Home/mobileAsset/images/tencent2018/video5.mp4" type="video/mp4">
</video>
```
That will render X5 video player unexpectedly.

We should set `x5-video-player-type` to `'h5-page'` Due to X5's documentation https://docs.qq.com/doc/DTUxGdWZic0RLR29B

## Expected Behavior【期望行为】

Page should render a video as browser-natived.

**Comment by toxic-johann** [comment]
Can you send me a pull request?

**Comment by joe223** [comment]
@toxic-johann Got an error

```shell
Cannot find module '../typings/base'
```

Is there any cmd or script to generate the missing `types` folder?

**Comment by toxic-johann** [comment]
Use this branch `v0.11.0`
