### ISSUE TITLE
在qq浏览器播放不了

### ISSUE THREAD

**Issue by GitHubLlj** [Chimeejs/chimee#36]
在qq浏览器/微信 播放不了

**Comment by songguangyu** [comment]
qq浏览器 是什么版本？

**Comment by GitHubLlj** [comment]
版本号：7.9.0.3638

**Comment by GitHubLlj** [comment]
我想在微信公众号上面用，是QQ浏览器 X5内核 7.9.0.3638，官网的DEMO在微信上打开也是播放不了

**Comment by songguangyu** [comment]
7.9.0.3638 是基于chrome 什么版本？
我这里测试 QQ浏览器9.7版本是没问题的，基于chrimium53.0.2785.104。
IE 模式 是不支持flv hls 直播点播的

**Comment by songguangyu** [comment]
如果是移动端 直接播放 hls 的流 不需要使用编解码器

**Comment by GitHubLlj** [comment]
我这里是在移动端的QQ浏览器，PC是没问题，

**Comment by GitHubLlj** [comment]
![image](https://user-images.githubusercontent.com/30815794/33113567-f42d7dd2-cf93-11e7-9596-a2e51e06ce80.png)
手机端的QQ浏览器可以贴一下代码吗？我的还是播放不了

**Comment by huzunjie** [comment]
@GitHubLlj 如果你是通过chimee.org看的，可以选择Box为native -- 使用移动环境原生支持的HLS解码试试。
![image](https://user-images.githubusercontent.com/3885060/33195380-ebb0f394-d111-11e7-8686-947566b5473f.png)

**Comment by GOGOGOSIR** [comment]
安卓微信下回强制全屏

**Comment by GOGOGOSIR** [comment]
能解决吗
