### ISSUE TITLE
文档中 video 属性 preload 可选值与默认值错误

### ISSUE THREAD

**Issue by yandeqiang** [Chimeejs/chimee#37]
[文档](https://github.com/chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#video属性)
preload 属性可选值／默认值错误
[video 属性 mdn](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video)
可选值， none/ metadata/auto 
默认值不同浏览器不同定义

**Comment by toxic-johann** [comment]
hmm。。。这里是当时特定选了 auto。。。。因为浏览器不同定义这个不同的有点混乱。

相当于我们这层强行定义的。

**Comment by toxic-johann** [comment]
如果没有太大问题的话先关闭了
