### ISSUE TITLE
使用 passive 模式监听部分事件

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#38]
![image](https://user-images.githubusercontent.com/6869168/33156944-7961a942-d039-11e7-88d8-e00cef2e70b8.png)
上面是chrome的log是否要做一下判断，移动端才监听这些事件？

**Comment by toxic-johann** [comment]
部分是移动端的。和移动端关系不大。部分代码加 passive 就好。

**Comment by toxic-johann** [comment]
此 issue 希望 @huzunjie 通过 [#1](https://github.com/Chimeejs/chimee-helper-dom/issues/1) 进行支持。

**Comment by huzunjie** [comment]
chimee-helper-dom 已修改并export supportsPassive 。

另外 defaultCapture = supportsPassive ? { passive: true } : false;

chimee-helper 也已升级发版，请试用~~
