### ISSUE TITLE
silentload 或者 load 的时候改变的如 isLive 等配置没有存到 videoconfig 中

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#40]
silentload 或者 load 的时候改变的如 isLive 等配置没有存到 videoconfig 中。因为没留意到其他插件也关注这个。

@yandeqiang 需要一个绑定了 islive 的插件我调试一下。

另外这个 islive 切换你有感知吗？

**Comment by yandeqiang** [comment]
目前已有的插件，没有感知， 直播点播切换状态的。 
我更新下 controlbar 吧
