### ISSUE TITLE
Some documents not ready?

### ISSUE THREAD

**Issue by JackPu** [Chimeejs/chimee#43]
I wonder if [how-to-write-an-ad-plugin.md](https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/how-to-write-an-ad-plugin.md) is ready?

**Comment by toxic-johann** [comment]
Hmm. yep.. It's not ready. But you can take a look at this [https://github.com/Chimeejs/chimee-plugin-popup/blob/master/README.md](https://github.com/Chimeejs/chimee-plugin-popup/blob/master/README.md)
