### ISSUE TITLE
kernel 事件没有被监听

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#44]
事件方法参见链接
https://github.com/Chimeejs/chimee-kernel

**Comment by toxic-johann** [comment]
https://github.com/Chimeejs/chimee/blob/master/src/helper/const.js#L100-L102

具体代码所在地。

**Comment by songguangyu** [comment]
done，辛苦随下次小版本发布。

**Comment by songguangyu** [comment]
发布在close吧

**Comment by toxic-johann** [comment]
看了下代码，问题还有点多。原来之前 kernelEvents 没有用到。

- [ ] 绑定事件
- [ ] 解绑事件
- [ ] silentload 切换时的动态重绑
