### ISSUE TITLE
全屏api与container设置冲突的问题

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee#49]
0.50以后可以对player.container进行设置 ，
比如我设置player.container.width=640px
 player.container.height=360px

当我点击全屏按钮后，浏览器进入全屏状态 container的区域还是640x360大小，没有铺满
chimee 是否应该自动接管这里，让container真正全屏，

全屏使用
方法 $fullscreen 
全屏的对象，可选video、container和wrapper
默认：container

按照一般的理解既然传入了区域，那么这个区域大小就得跟全屏的大小一样才对

**Comment by toxic-johann** [comment]
这个和布局的 css 可能还有强关联。感觉应该要加多个选项。

如 fullscreen(flag, target, { forceMax: true }) 强制最大化

或者 fullscreen(flag, target, { omitWidth: true }) 忽略 chimee 的宽高设置。
