### ISSUE TITLE
移动 video 容器时迷之触发 ended 事件和 paused 事件

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#5]
silentLoad 方法在 immediate 时 没有把 kernel destory。 有可能导致内存泄露。

**Comment by toxic-johann** [comment]
@songguangyu old video 的 remove 在 switchkernel 阶段执行。应该不是这个问题。

**Comment by toxic-johann** [comment]
@songguangyu 或者给个复现环境我帮你们看看？

**Comment by toxic-johann** [comment]
暂无法复现。

**Comment by toxic-johann** [comment]
复现场景： windows chrome 61

触发 paused 场景，将一个播放中的 video 移动位置。

**Comment by huzunjie** [comment]
ended 与hls重试有关，已暂时禁用..
https://github.com/Chimeejs/chimee-kernel/blob/master/src/index.js#L101

**Comment by huzunjie** [comment]
ended 与hls重试有关，已暂时禁用..
https://github.com/Chimeejs/chimee-kernel/blob/master/src/index.js#L101

**Comment by toxic-johann** [comment]
所以。就是定位到了 bug 的意思？
