### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by willin** [Chimeejs/chimee#50]
![lalpbbcc1ta0mi0-zqi-_574_62 png_620x10000q90g](https://user-images.githubusercontent.com/1890238/33533302-389480ec-d8db-11e7-9a56-e3623795a44f.jpg)

![lalpbbcc1tazcaqzzqiz_537_51 png_620x10000q90g](https://user-images.githubusercontent.com/1890238/33533303-391a161c-d8db-11e7-8463-436a559a97d9.jpg)

when error occured, this player crashed and never roll back again

cc @solocao @zhangyf92

**Comment by songguangyu** [comment]
chimee have error event, user need listen this event, when error occured, developer need roll back by themself.

**Comment by songguangyu** [comment]
flv event list https://github.com/Chimeejs/chimee-kernel/blob/master/readme.md

**Comment by h371535926** [comment]
这么怎么解决啊?

**Comment by songguangyu** [comment]
@h371535926  chimee可以监听 网络错误error，如果是网络错误，可以重新 load 就可以了。
