### ISSUE TITLE
先引用编译后的js在写入video的wrapper，全屏按钮会报错

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee#51]
一个html页面里面先引用的js 再写div容器，这时点全屏会报错
<script>xxx/index.min.js</script>
`<div id=‘wrapper’ class=‘bfvcontainer’<video tabindex=‘-1’></video></div>`

如果先写div容器再引用js 点全屏就不会报错
`<div id=‘wrapper’ class=‘bfvcontainer’<video tabindex=‘-1’></video></div>`
<script>xxx/index.min.js</script>）

**Comment by toxic-johann** [comment]
额。。。不是很理解。给个代码？

**Comment by hxzpily2** [comment]
修改完了

**Comment by toxic-johann** [comment]
哦……就是如果先引入 script ，会有部分功能报错。我今晚验证一下。

**Comment by toxic-johann** [comment]
尝试了一下 chimee 的 script 标签移到最开始并不会报错。

请问你调用的是 chimee 还是 chimee-player 呢？另外是在什么浏览器上调用呢？具体报什么错呢？

**Comment by hxzpily2** [comment]
chimee-player

**Comment by toxic-johann** [comment]
报什么错？
