### ISSUE TITLE
chimee-plugin-ui

### ISSUE THREAD

**Issue by RyanPoy** [Chimeejs/chimee#53]
找不到 chimee-plugin-ui
直接用：import ui from 'chimee-plugin-ui' 报错。
后通过：npm install import chimee-plugin-ui
提示：
npm ERR! code E404
npm ERR! 404 Not Found: chimee-plugin-ui@latest

**Comment by toxic-johann** [comment]
额。。。。目前的确没有 chimee-plugin-ui 。。。我换个示例吧
