### ISSUE TITLE
chimee与内部kernel，plugin等通信的一致性问题

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee#54]
因目前有内部项目需要，所以目前选择fork了chimee的部分内容，然后发现有些可以改进的地方，希望可以讨论下
1.对于外层config向内传递方式。
目前内部每一个可能使用的class全部在constructor中自行进行备份以及维护，这样比较容易产生一些无法发现的问题，比如昨天我在使用fork下来的chimee-flv2mp4的时候踩了一个坑https://github.com/Chimeejs/chimee-flv2fmp4/issues/5
2.对于事件上报的机制的统一
目前在chimee以及各个kernel内部实现时，有两种方式，第一种，通过继承CustEvent然后做层层上报，另一种是透传callback直接到下层，两种方式都各有利弊，以及这种方式根源可能出在chimee内部处理层级纵深较深，所以是否有考虑这块有没有更优化的方式

@toxic-johann

**Comment by toxic-johann** [comment]
修改 chimee-kernel 后发现 kernel 层的配置确实比较混乱。

而且每一个层级都在全量复制。

近段日子会进行梳理定制相关规范。

**Comment by toxic-johann** [comment]
暂时通过 config 和 custom-config 传递

kernel 层事件通过 custom events 传递
