### ISSUE TITLE
load 及 slientload 方法改造

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#55]
@songguangyu 提供需要重启 kernel 的相关环境。

以及天翔建议的目前config里面其实就有src了，所以是否考虑load的时候不一定有第二个参数，如果是string，就当作src，如果是obj，就当错config解析，路径用config.src

另外 load 的时候需要支持给各个 kernel 做参数的支持。现有额外参数需要提供给 kernel 层。

关联问题[https://github.com/Chimeejs/chimee/issues/39](https://github.com/Chimeejs/chimee/issues/39)

相关参数示例

![](https://ws4.sinaimg.cn/large/006tNc79gy1fm8he87anbj317g0xmagp.jpg)

- [x] load 的时候对于要重建 kernel 的情景自动进行 kernel 切换
- [x] 支持传递特定的参数到 kernel 中去
- [x] chimee-kernel 支持 presetConfig
- [x] 支持单独对象传入的 api

**Comment by skyline0705** [comment]
希望增加对kernel-flv增加stashSize字段，用于控制缓存大小

**Comment by toxic-johann** [comment]
chimee 现已支持 presetConfig， 但是观察 chimee-kernel 及 chimee-kernel-flv 还是比较混乱。双方需要结合一起解决。

与 [https://github.com/Chimeejs/chimee/issues/54](https://github.com/Chimeejs/chimee/issues/54) 相关。

希望能做一个简单的梳理吧。

**Comment by toxic-johann** [comment]
chimee 层会将相关配置以如下形式传给 kernel 层。

```json
{
    preset: {
       flv: Function
    },
    presetConfig: {
      flv: Object
    },
}
```

所以在  kernel 中建议根据自己选中的 box ，读取配置，并保存在实例上。

现在假设该配置在运行中不能更改。

**Comment by toxic-johann** [comment]
@skyline0705 已支持 kernel 自定义配置。相见文档 [https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#-kernels](https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#-kernels)

**Comment by toxic-johann** [comment]
published in 0.7.1
