### ISSUE TITLE
Chimee 不支持初始化的时候传递自定义的settings

### ISSUE THREAD

**Issue by RyanPoy** [Chimeejs/chimee#56]
例如：
new Chimee({
        wrapper: '#player',
        src: url,
        poster: poster,
        controls: true,
        autoplay: true,
        box: 'hls',
        kernels: { flv, hls },
        customer_config_1: xxxx
});
这里的customer_config_1 就是自定义的settings

**Comment by toxic-johann** [comment]
具体需要的定义值是什么？作用是什么？传递到哪里去呢？

**Comment by RyanPoy** [comment]
简单的说，就是在最终生成html的时候，在标签里面能够把自定义的内容渲染出来。这种做法主要是应用在很多时候，我们需要对某些标签加入一下自定义的东西。例如 data=xxx，例如 remote-uri=xxx 。这么做，是在很多场景下，当我拿到这个标签，我就能拿到自定义的一些属性，做处理。
