### ISSUE TITLE
移动端vue项目接入报错：Cannot read property 'readyState' of null 

### ISSUE THREAD

**Issue by pengandpeng** [Chimeejs/chimee#59]
移动端vue项目接入报错：Cannot read property 'readyState' of null 
![](https://raw.githubusercontent.com/pengandpeng/markdown-images/master/images/123.png)

**Comment by toxic-johann** [comment]
额。。引入的具体库、版本？

你是引用了 chimee-kernel-hls 吗？

有复现环境吗？

**Comment by songguangyu** [comment]
如果是移动端项目 需要把box 设置为native 并且不需要引入任何解码器。

**Comment by pengandpeng** [comment]
问题解决了，原来是引入的mock.js有影响

**Comment by toxic-johann** [comment]
嗯。好的。

**Comment by yoyo0926** [comment]
你好，我也遇到这种情况了，请问是哪里的mock有影响，我并没有引入mock.js哎
