### ISSUE TITLE
关于 isSupport 的编写

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#6]
@huzunjie @332065255 @songguangyu 

观察到 kernel 里的 isSupport 是指该 kernel 是否运行。 Chimee 层的 isSupport 各位是期望遍历所有安装的 kernel 是否运行吗？ 感觉有点怪。

**Comment by songguangyu** [comment]
@toxic-johann kernel isSupport 方法改写一下，内部做好各个插件的判断，稍后提交新版本解决次问题

**Comment by toxic-johann** [comment]
@songguangyu 所以是希望根据地址给出结果对吧

**Comment by toxic-johann** [comment]
等待 kernel 层 api 更改再作决定
