### ISSUE TITLE
使用chimee-mobile-player能加载视频，但是不能自动播放，点击播放后全屏播放

### ISSUE THREAD

**Issue by pengandpeng** [Chimeejs/chimee#60]
使用chimee-mobile-player能加载视频，但是不能自动播放，点击播放后全屏播放

**Comment by toxic-johann** [comment]
手机型号，浏览器。

**Comment by pengandpeng** [comment]
iphone 8 ,ios11，微信浏览器

**Comment by yandeqiang** [comment]
playsInline: true,
    preload: true,
    x5VideoPlayerFullscreen: true,
    x5VideoOrientation: true,
    xWebkitAirplay: true,
    muted: true

**Comment by pengandpeng** [comment]
好的，我去试一下

**Comment by pengandpeng** [comment]
顺便问一下，没有提供销毁播放器实例的api呢

**Comment by yandeqiang** [comment]
@toxic-johann 文档好像没有找到唉，
调用 `player.destroy()` 就好了

**Comment by toxic-johann** [comment]
@yandeqiang 提个 pr 吧
