### ISSUE TITLE
移动端qq浏览器视频加载失败

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#61]
http://chimee.org/     这个官网上面的也是，你试一下 用 qq浏览器打开， 视频处与一直加载的状态，然后过一会显示加载失败     环境是 苹果8 ios11  qq浏览器

**Comment by soulToken** [comment]
微信浏览器里面也是 会一直加载 但是不会失败， 视频上一直有一个loading 动画，需要手动点击播放才会播放

**Comment by huzunjie** [comment]
移动环境中，存在不自动载入、开始播放的情形，从而导致不触发 playing timeupdate 事件，所以PC版不适用移动端，如果有应用需求可以使用移动版 [https://github.com/Chimeejs/chimee-mobile-player](https://github.com/Chimeejs/chimee-mobile-player) .

**Comment by soulToken** [comment]
您好， 移动版我想引入 js 的形式， 这个js 路径是什么？ 不想用node 构建的方式

**Comment by huzunjie** [comment]
@soulToken 可以直接将 https://github.com/Chimeejs/chimee-mobile-player/blob/master/lib/chimee-mobile-player.browser.js 放置在您的项目里引用，具体用法可以[参考相应文档](https://github.com/Chimeejs/chimee-mobile-player/blob/master/README.md)。

**Comment by soulToken** [comment]
有没有像 pc 端 https://s3.ssl.qhres.com/!eb3eaf2c/chimee-player.js  这样一样的路径， 这个 github 路径是不是需要下载下来 放到 项目中引用啊 ，    类似cdn网址 有没有？

**Comment by yandeqiang** [comment]
http://s7.qhres.com/!b0c9d54a/chimee-mobile-player.min.js 传到静床了， 可以看下

**Comment by soulToken** [comment]
html 是<div class="chimee-container" id="wrapper">
    <video tabindex="-1"></video>
</div>


引入相应的js  然后在 在 script 变迁里面 
加入  new ChimeeMobilePlayer({
  wrapper: '#wrapper',  // video dom容器
  src: 'http://cdn.toxicjohann.com/lostStar.mp4',
  autoplay: true,
  controls: true,
  playsInline: true,
  preload: true,
  x5VideoPlayerFullscreen: true,
  x5VideoOrientation: true,
  xWebkitAirplay: true,
  muted: true
});

但是结果会报这个错误
Uncaught TypeError: Cannot read property 'DEFAULT_DISABLE_UA' of undefined
    at new r (chimee-mobile-player.min.js:7)
    at viedo.html:47

**Comment by soulToken** [comment]
html 是<div class="chimee-container" id="wrapper">
    <video tabindex="-1"></video>
</div>

**Comment by soulToken** [comment]
html是
“”  <div class="chimee-container" id="wrapper">
    <video tabindex="-1"></video>
</div>  “”

**Comment by yandeqiang** [comment]
http://s1.qhres.com/static/4403e2029b213c98.js 
先用这个，min.js 确实有些问题，我再看看。

**Comment by soulToken** [comment]
好的， 非常感谢哈， 你们是在太棒了
