### ISSUE TITLE
能不能给一个不用node,直接在页面引用的例子?

### ISSUE THREAD

**Issue by mike8625** [Chimeejs/chimee#62]
jq项目不用node,能给个直接引用的例子吗?

**Comment by toxic-johann** [comment]
```html
<script src="/path/to/chimee/lib/index.browser.js"></script>
```

直接引用 index.browser.js 或者 index.min.js 即可。

**Comment by toxic-johann** [comment]
额。能解决问题吗？

**Comment by toxic-johann** [comment]
index.browser.js [https://raw.githubusercontent.com/Chimeejs/chimee/master/lib/index.browser.js](https://raw.githubusercontent.com/Chimeejs/chimee/master/lib/index.browser.js)

index.min.js [https://raw.githubusercontent.com/Chimeejs/chimee/master/lib/index.min.js](https://raw.githubusercontent.com/Chimeejs/chimee/master/lib/index.min.js)

**Comment by mike8625** [comment]
sorry, 这两天有事没看git, 可以了,解决了,十分感谢!
