### ISSUE TITLE
您好，移动端， 点击屏幕 播放 停止 切换，需要自己来写嘛？

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#63]
还有一个问题， 在 ios 11  底部有输入框的情况下，点击全屏，  视频并没有遮蔽  底部输入框 ， 底部输入框并没有设置 z-index   这是怎么回事？

**Comment by toxic-johann** [comment]
输入框是你自己的吗？还是是一个 chimee 的插件？有相关的 demo 可以看看吗

**Comment by soulToken** [comment]
输入框是自己的  position:absolute 定位到底部的  页面只分为两部分， 上面跟底部， 本地测试的 所以 没法看

**Comment by yandeqiang** [comment]
题目是什么意思啊？ 控制条想要增加这几个按钮？

**Comment by toxic-johann** [comment]
如果输入框不是 chimee 插件的话我们不会进行相关设置哦。

**Comment by soulToken** [comment]
题目的意思是 我点击正在播放的视频 他不会停止， 只有点急 左下角 按钮才会 停止，反过来也是这样。

**Comment by soulToken** [comment]
我说的输入框的意思是， 点击全屏播放的话，不是会盖住页面的所有元素嘛 ，  手机上 怎么 底部的输入框没有盖住 。

**Comment by yandeqiang** [comment]
这个是看友商这么搞得， 你也可以看下，应该是为了防止用户误触吧。

**Comment by toxic-johann** [comment]
哦。。。所以是两个问题。。。移动端提供了手势吧?

**Comment by yandeqiang** [comment]
是的。 提供了手势， 可以点击的。 监听 tap 事件就好了

**Comment by soulToken** [comment]
非常感谢 你们可以这么耐心的 为我们解答 问题。
