### ISSUE TITLE
H5支持推流

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#65]
H5支持推流，是否可以考虑美颜，人脸等需求。欢迎一起讨论。

**Comment by toxic-johann** [comment]
这个感觉应该在流里做？

**Comment by songguangyu** [comment]
就是在端上做，对流进行处理。

**Comment by toxic-johann** [comment]
端上做算力不一定足够吧。不过可以试试的 2333。为未来储备。

**Comment by songguangyu** [comment]
嗯 可以调研一下 后面没准chimee 不光是播放器了，而是直播娱乐的整体解决方案呢。

**Comment by toxic-johann** [comment]
yep。不要太局限。

**Comment by losingle** [comment]
美颜，人脸等需求，我觉得应该由第三方库或者服务来做。
chimee 有扩展点就可以了。
大而全，难以权衡，容易忘掉最重要的。

**Comment by toxic-johann** [comment]
@losingle 嗯。在你的理解里，你觉得 chimee 的核心是什么呢？

另外对于 chimee 的扩展点，现阶段是否足够呢？还有没有一些比较不满意的点，或者希望增加的点。

**Comment by songguangyu** [comment]
@losingle 在美颜 人脸等东西 肯定是使用第三方库，因为我们不可能做每一个事情，但是我们会调研，选用相对优质的库，并能够有一定解决问题的能力。

**Comment by losingle** [comment]
我也这么认为，只有这样才能把产品的重点做好
