### ISSUE TITLE
全景（panorama）视频的支持

### ISSUE THREAD

**Issue by losingle** [Chimeejs/chimee#66]
非常棒！😊
请问有支持 [panorama video](https://yanwsh.github.io/videojs-panorama/) 的计划吗？

**Comment by toxic-johann** [comment]
啊。感谢。我们调研一下～

**Comment by songguangyu** [comment]
全景（panorama）视频 有什么特殊点吗？

**Comment by songguangyu** [comment]
@losingle 全景（panorama）视频 是个非常好的点，我们稍后给个方案，非常感谢。

**Comment by losingle** [comment]
很棒，期待。

**Comment by toxic-johann** [comment]
可以尝试使用[chimee-plugin-panorama](https://github.com/Chimeejs/chimee-plugin-panorama/releases/tag/0.1.0) 。有相关需求可以提出。我们会持续优化这个插件。
