### ISSUE TITLE
TypeScript 声明文件的支持

### ISSUE THREAD

**Issue by losingle** [Chimeejs/chimee#67]
我又来提Issue了 😢
发现 @types 里面还没有 chimee 的声明文件
想要自己写一个，但是发现 gitignore 里面有 Typescript v1 declaration files。
是不是有现成的没有提交呢？那样就不用重复写了 😊

**Comment by toxic-johann** [comment]
还没有的。当时侯是 vscode 出了点问题加的。可以参考 flow.js 写一个。

**Comment by toxic-johann** [comment]
moved to https://github.com/Chimeejs/chimee/issues/119
