### ISSUE TITLE
chimee 里的 log 如何调节

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#7]
提供文档或者提供功能。

**Comment by toxic-johann** [comment]
这个是插件才允许使用的后门。还是说提供给业务方的临时关闭措施呢？

就是说 chimee 的直接用户是否也可以调用这个规则。

**Comment by huzunjie** [comment]
插件才允许使用，文档里要公开的话要明确说明必须保证操作无害才可以启用... 要不这个设计的初衷就可以直接废弃了。

**Comment by toxic-johann** [comment]
看了下，现行的方式是直接可以在[ chimee-helper-log ](https://github.com/Chimeejs/chimee-helper-log)中直接调节。其实原理上对 log 这方面确实没怎么包装。用户和插件都可以直接通过修改这个对象达到目的。

**Comment by toxic-johann** [comment]
@huzunjie chimee 原有的 log 应该能满足你的需求。插件内部自己更改也是可以的。

因为之前没有将具体文档提供出来，文档[在此](https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/chimee-api.md#log)。
