### ISSUE TITLE
暴露 stopLoad 的接口

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#70]
暴露 hls.js 的 stopload 接口

临时方案，hls.js 使用 player.__dispatcher.kernel.videokernel.hls.stopLoad

chimee-kernel-flv 使用 player.__dispatcher.kernel.videokernel.stopLoad

相关更改有如下几个

chimee

- [ ] startLoad
- [ ] stopLoad

chimee-kernel

- [x] startLoad
- [x] stopLoad

chimee-kernel-hls

- [x] startLoad
- [x] stopLoad

chimee-kernel-flv

- [x] stopLoad

chimee-kernel-flv.js

- [x] stopLoad

**Comment by songguangyu** [comment]
下个小版本chimee 统一加 stopLoad 吗？

**Comment by toxic-johann** [comment]
是的。会在下个版本加。应该在这周。
