### ISSUE TITLE
flv直播时，没有audio导致无法播放

### ISSUE THREAD

**Issue by h371535926** [Chimeejs/chimee#73]
flv直播时，没有audio导致无法播放

**Comment by songguangyu** [comment]
没有audio 也是可以播的 如果方便 提供下直播流

**Comment by h371535926** [comment]
稍等，因为我用flv.js的demo来播放的话，不勾选hasAudio 就可以播放，所以就有这样的疑惑，谢谢

**Comment by h371535926** [comment]
http://116.205.13.37:8082/live/34020000001310000001.flv   @songguangyu

**Comment by songguangyu** [comment]
OK 我来跟进一下

**Comment by songguangyu** [comment]
@h371535926  681806019 这个是我们QQ群 你加到群里 咱们方便沟通

**Comment by toxic-johann** [comment]
@h371535926  请问现在问题解决了吗？

**Comment by songguangyu** [comment]
@h371535926 经过沟通应该是cdn 不规范引起的
