### ISSUE TITLE
是否有接口可以取到直播流当前的 buffer

### ISSUE THREAD

**Issue by musicode** [Chimeejs/chimee#74]
观看端要根据直播流的 buffer 延迟执行一些动作，需要这个 buffer 值，请问是否能取到呢

**Comment by toxic-johann** [comment]
是什么直播呢？

**Comment by musicode** [comment]
教育类的直播，就是想在直播时，获取 buffer，比如推流端说了一句话，到拉流端可能要 1 秒后，但是信令是实时到达的，所以为了保证语音和信令同步，需要延时执行

**Comment by toxic-johann** [comment]
直播的流类型。是 m3u8 还是 flv 呀？

**Comment by musicode** [comment]
都有

**Comment by toxic-johann** [comment]
chimee.buffered 看看能不能解决问题？[https://github.com/Chimeejs/chimee/blob/f46dcb42c4cf3541c7c2ac20feb93f1a9b8ee69a/doc/zh-cn/chimee-api.md#buffered](https://github.com/Chimeejs/chimee/blob/f46dcb42c4cf3541c7c2ac20feb93f1a9b8ee69a/doc/zh-cn/chimee-api.md#buffered)
