### ISSUE TITLE
如何监听 全屏事件与退出全屏事件

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#75]
因为现在涉及到  全屏 的时候，我自己写的底部输入框会盖住 底部全屏还有快进的按钮， 所以我现在想监听全屏事件与退出全屏事件，  
var player=new ChimeeMobilePlayer({
              wrapper: '#wrapper',  // video dom容器
              src: 'http://cdn.toxicjohann.com/lostStar.mp4',
              autoplay: false,
              controls: true,
              playsInline: **true,**
              preload: true,
              x5VideoPlayerFullscreen: true,
              x5VideoOrientation: true,
              xWebkitAirplay: true,
              muted: true,
              penetrate:true,
              exitFullscreen:function(){
                  alert(1)    #  **_//退出全屏事件不执行，这里应该怎么监听_# **
              },
          });

**Comment by soulToken** [comment]
var player=new ChimeeMobilePlayer({
              wrapper: '#wrapper',  // video dom容器
              src: 'http://cdn.toxicjohann.com/lostStar.mp4',
              autoplay: false,
              controls: true,
              playsInline: true,
              preload: true,
              x5VideoPlayerFullscreen: true,
              x5VideoOrientation: true,
              xWebkitAirplay: true,
              muted: true,
              penetrate:true,
              c_on:{
                  "play":function(){
                    alert('ok')
                  }
              },
              events: {
                
                 play () {
                    console.log('play!!');
                  }
              }
          });
  在event 里面  或者 on 里面  w_on里面。 c_on里面  监听 都没用啊，    所以 监听相应的事件要怎么处理？

**Comment by toxic-johann** [comment]
player.on('fullscreenchange', evt => console.log(evt))

**Comment by toxic-johann** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fnf56y1nzig30r60h0he4.gif)
