### ISSUE TITLE
怎么样对视频进行加密处理？

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#79]
h5应用的画，在 审查元素的时候是可以直接再video 标签中看到视频的连接的。 而视频是存储在阿里云上的，这样 直接再浏览器中打开是可以直接去下载该视频的，我想请问一下，我怎么样禁止第三方来下载这个视频，阿里云的视频防盗链的话  ，在未授权的域名下时，就可能不能正常的观看，但是这个视频文件如果被下载，是可以直接通过播放器来观看的，因为该文件本身没有做加密的。总之，怎么可以做到视频加密？？？

**Comment by songguangyu** [comment]
如果是非常重要的视频，有很强的版权的话，建议使用Flash进行播放。
如果是一般的直播、点播。没有很强的版权，CDN开始防盗链就可以了。
