### ISSUE TITLE
使用此播放器播放存储在腾讯云的flv，播放不了，但是这个flv地址通过其他播放器是可以的

### ISSUE THREAD

**Issue by solocao** [Chimeejs/chimee#8]
flv地址：http://1253804432.vod2.myqcloud.com/3712977fvodgzp1253804432/f3f31e5f9031868223411915443/f0.flv

vlc播放成功、腾讯tcplayer也能播放。
<img width="857" alt="2017-11-06 4 21 17" src="https://user-images.githubusercontent.com/11675718/32431670-50f69f12-c30f-11e7-9ccb-9440e25480dc.png">
使用chimee播放报错。
```
Failed to load http://1253804432.vod2.myqcloud.com/3712977fvodgzp1253804432/f3f31e5f9031868223411915443/f0.flv: Response for preflight has invalid HTTP status code 400

```
<img width="1408" alt="2017-11-06 4 22 37" src="https://user-images.githubusercontent.com/11675718/32431683-597d2106-c30f-11e7-8629-2e0ef2901a5c.png">

麻烦团队大牛帮我看一下，是解码器的问题吗？

**Comment by toxic-johann** [comment]
提供一个线上[复现环境](https://codepen.io/toxic-johann/pen/ooLMbm)。

看上去像是视频源的问题。

@songguangyu 关注一下。

**Comment by huzunjie** [comment]
@solocao 需要您确认一下腾讯云的视频资源是否有开启防盗链拦截？ 通过现象看是服务端直接拒绝了视频资源请求。

**Comment by songguangyu** [comment]
nginx 请求需要配置 OPTIONS， nginx 在请求时需要配置跨域请求header

**Comment by songguangyu** [comment]
看了一下视频流 只有视频 没有音频， 这个问题会在下个小版本 修复次问题。感谢 @solocao 的反馈 ！
@332065255 编解码那块需要支持一下。

**Comment by songguangyu** [comment]
@solocao chimee-kernel-flv@1.2.2  chimee-kernel-flv模块更新到1.2.2 可以支持only video 模式

**Comment by solocao** [comment]
换成最新包已经解决了播放问题。还有一个问题，就是现在获取视频资源会先发预检请求，腾讯云的链接资源是可以下载的，但是会报跨域的错。
```
Failed to load http://1253804432.vod2.myqcloud.com/3712977fvodgzp1253804432/f3f31e5f9031868223411915443/f0.flv: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:10001' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
可以提供其他的请求配置吗。解决一下这个跨域问题。(PS 要是存放到自己服务器，我们会服务器端配置，但是腾讯云控制台没有看到相关配置功能，只有个白名单、黑名单)，其他某些flash播放器，是直接可以播放的额。

**Comment by songguangyu** [comment]
下一版会支持 start end 的get 参数查询
