### ISSUE TITLE
怎么样检测到视频 加载完毕

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#80]
现在是这样的， 后台那边是不返回 视频时长的， 但是我调用相应的方法的时候，返回值 可能是undefined， 查找一下原因，可能是因为视频还未加载完毕，    那么有没有相应的方法，等视频加载完毕的时候我再去， 调用这个方法，然后去改变相应的 html 内容？？？

**Comment by songguangyu** [comment]
loadedmetadata 事件后 获取一下试一试

**Comment by soulToken** [comment]
chimee () {
        var self=this;
          // src: 'http://cdn.toxicjohann.com/lostStar.mp4',
          var player=new ChimeeMobilePlayer({
              wrapper: '#wrapper',  // video dom容器
              src: 'http://cdn.toxicjohann.com/lostStar.mp4',
              autoplay: false,
              controls: true,
              playsInline: true,
              preload: true,
              x5VideoPlayerFullscreen: true,
              x5VideoOrientation: true,
              xWebkitAirplay: true,
              muted: true,
              penetrate:true
          });
          // player.exitFullscreen=function(){
          //   console.log(1)
          //   debugger;
          // }
        player.on('fullscreenchange', evt => 
        // console.log(evt)
        //将输入框取反
          self.fullscreenchange=!self.fullscreenchange
        )
        player.on('loadedmetadata', evt => {
          self.durationTime=this.duration;
          debugger;
            }
        
        )
    },
 您好是这样写的嘛？ 不知道为什么 在页面上得到的总是 undefined

**Comment by songguangyu** [comment]
@soulToken 视频是否加载完成 这个很难区分，因为视频可能是分段加载的。但是你可以用buffered 和 总时长进行对比。

**Comment by soulToken** [comment]
player.on('loadedmetadata', evt => {
          let time=0;
debugger;
          time=this.duration;
          window.durationTime=time
          debugger;
            }
        )
您好， 我在第一个debugger 那边 获取生命的time值 为何 会是undefined ？  我明明赋值为零的啊

**Comment by songguangyu** [comment]
this.$video. duration 试一试？

**Comment by soulToken** [comment]
player.on('loadedmetadata', evt => {
              //  var time=self.timeFormate(this.duration)
              debugger;
          // self.durationTime=this.duration;
          
         let time=this.$video. duration;
        console.log(time)
          debugger;
            }
        
        )
  我这写法没有什么问题吧？   为什么 会报错
uncaught (in promise) TypeError: Cannot read property 'duration' of undefined
    at t.eval (video.vue?23c2:477)
    at i (4403e2029b213c98.js:1)
    at 4403e2029b213c98.js:1
    at <anonymous>
但是我在 调试的时候 console 里面输入this.$video. duration是可以获取到值的，   我感觉这个方法里面写东西碰到了很多诡异的东西。

**Comment by songguangyu** [comment]
不要用箭头函数 请使用function() {} ，具体请参考 http://es6.ruanyifeng.com/#docs/function#%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0 
阮一峰的 es6 箭头函数说明。
