### ISSUE TITLE
chimee 切换清晰度的时候重置属性引起诸如 volumnChange 等无关事件

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#82]
例如有个小例子，比如我在音量改变的的时候，会在屏幕上显示一个动画。
但是现在chimee初始化的时候就会触发volumeChange，或者在切换清晰度的时候 也一样会触发 volumeChange的改变。
我的想法是这样的，在config里如果不设置volume 那么chimee也不主动的去设置volume，这样就不会触发volumeChange事件。
主要考虑的是，我们播放器是否更贴合原生的video的一些行为。欢迎一起讨论一下

**Comment by toxic-johann** [comment]
我的想法是这样的。

## 初始问题

这个问题是因为初始化的时候我们会去设定一些值，但是这些值有可能会触发一些事件，导致开发者在行为处理的时候有歧义。

## 问题拆分

我们现在插件的生命周期如下：

beforeCreate -> create -> init -> inited -> destroy

而 video 数据初始化发生在 init -> inited 之间。

所以准确来说，开发者要避免这个问题，**可以选择在 inited 阶段再监听事件**。

但事实上，我们在文档中是**鼓励开发者在 create 阶段绑定事件**的。

这就造成了如 @songguangyu 反映的问题。

## 问题解法

那这个问题其实是有好几个解法的。我们逐一分析

### 1. 默认值有就通知，没有不通知

这个方法其实我不太赞成。因为这种行为其实十分怪咖。开发者设置了默认值反而会有事件让他进行处理，就很懵逼。这个逻辑不太正常。

开发者的根本目的不是是否设置默认值，其实他的初始目标是**初始化的时候这种变化不应该通知我**。

但是我们要考虑到的是，开发者可能会在某些时候需要这个初始化的事件。。。所以我认为也不应该一刀切。

### 2. chimee 增加参数，在初始化期间事件不上传

这个方法是可以加的，而且我们也可以支持对特定的事件才做这种处理。但是在代码逻辑上增加了一些别扭的处理吧。

### 3. 鼓励开发者将这类事件的绑定放在 inited 中处理。

这个是一个比较可行的状态。整个 chimee 初始化完成是在 inited 阶段结束后。所有插件的 inited 完成后，ready 被 resolve， readySync 变为 true。如果认同这个生命周期的用法，我们可以修改下文档。

### 4. 插件内部根据 chimee 的 ready 和 readySync 标志位做判定。

这种也是特殊插件特殊处理的方式，插件认为初始户期间不应该处理这个事件，就不要处理。


综上所述，我建议开发者可不可以考虑方法 3，方法 4 进行处理。因为我们在框架层，开发者编写的时候就可以手动避免这种通知。

当然，这种事件是不是特别多呢？我们是否需要默认就不通知呢？这个也要商量一下。如果这个事件比较特殊，情况比较少。我建议让开发者采用 3/4 做法。

**Comment by songguangyu** [comment]
chimee的inited生命周期 会错过 video 相关的生命周期吗？这块我不是太熟。

**Comment by songguangyu** [comment]
比如像我issue里提的 切换清晰度，事件是提前已经绑定好了的，我在切换清晰度的时候会触发 volumeChange 这个情况，这个是个明显和合理的情况吧？

**Comment by toxic-johann** [comment]
错过什么周期？？有可能的，例如你设置了 autoplay，确实会错过某些东西。

所以其实用 ready 判断比较好。

**Comment by toxic-johann** [comment]
silentload 确实应该屏蔽这层事件，我加多个处理。除了 volume change 还有什么事件有这个问题。

这个问题并不是根据初始值通知。切换 kernel 也是一样的，开发者设置了默认值就会收到通知。

所以类似切换清晰度这种需求。我们通过事件隐藏来解决问题就好。

**Comment by songguangyu** [comment]
其他的我暂时还没有发现，发现了会在此issue 上进行追加。
