### ISSUE TITLE
支持websocket协议的flv流吗

### ISSUE THREAD

**Issue by Panhaiwei** [Chimeejs/chimee#86]
支持websocket协议的flv流吗~

**Comment by toxic-johann** [comment]
支持的

**Comment by songguangyu** [comment]
@Panhaiwei 流地址方便提供给我一下吗？我看一下

**Comment by Panhaiwei** [comment]
@songguangyu  流是本地服务器.. 使用谷歌开发者工具中的network可以抓到websocket一直再推送数据，同时我使用bilibili 的flv.js 是可以正常播放的，
![image](https://user-images.githubusercontent.com/13009686/35715738-4db33cda-080f-11e8-89aa-e9eade28afaf.png)
![image](https://user-images.githubusercontent.com/13009686/35715750-5ed88e48-080f-11e8-8d89-6cf81463171c.png)

**Comment by songguangyu** [comment]
@Panhaiwei 你看这个src 对吗？能否提供个ws 流 我测试一下

**Comment by songguangyu** [comment]
有报错信息吗？

**Comment by Panhaiwei** [comment]
@songguangyu 没有报错，一直在发heartbeat，我去找找有没有线上的ws流

**Comment by songguangyu** [comment]
@Panhaiwei 好的

**Comment by songguangyu** [comment]
@Panhaiwei 你本地是怎么搭的 如果方便是开源的 我也搭建一个

**Comment by Panhaiwei** [comment]
@songguangyu 不好意思现在才回复你，我这边的流媒体服务器暂时没办法搭建到其他地方，我会找时间js再次测一下，看看能否找到什么问题 谢谢

**Comment by songguangyu** [comment]
@Panhaiwei chimee-kernel-flv@1.4.9 麻烦请更新到最新版本 修复了websocket 的bug

**Comment by Panhaiwei** [comment]
@songguangyu 我git clone了最新的chimee-kernel-flv版本，并且使用了你的chimee-kernel-flv中的demo进行测试，还是无画面，看起来像是并没有抓到流，可是我使用谷歌开发者工具抓取websocket的包还是有数据流一直在发送..

**Comment by Panhaiwei** [comment]
@songguangyu 
监听事件中，并没有触发mediaInfo和error，
![image](https://user-images.githubusercontent.com/13009686/35791945-57bba97e-0a85-11e8-9807-8c7b6a11105b.png)

**Comment by songguangyu** [comment]
@Panhaiwei 稍等 我在更新一版

**Comment by songguangyu** [comment]
@Panhaiwei 麻烦重新clone 一下 或者  npm 更新chimee-kernel-flv@1.4.10

**Comment by Panhaiwei** [comment]
@songguangyu ok，该版本测试通过，正常出画面了

**Comment by songguangyu** [comment]
@Panhaiwei 好的 谢谢 有问题可以在反馈给我们
