### ISSUE TITLE
在ios app 里面 一直是加载状态，必须要手动点击一次播放才能正常显示 ， 还有就是播放 在ios 安卓都没声音 

### ISSUE THREAD

**Issue by soulToken** [Chimeejs/chimee#87]
具体地址可以看一下  http://120.79.176.171:8080/100care_server/resources/static/htmls/index.html#/video?plan=%7B%22mobile%22%3A%2215919901868%22,%22token%22%3A%226d2901d4e6943c8af32767c39a6f628f%22,%22titleId%22%3A%228%22,%22titleType%22%3A%221%22%7D             我想问一下这个是我代码使用有问题还是什么？ 谢谢了。

**Comment by soulToken** [comment]
https://user-images.githubusercontent.com/30686262/36022038-961cf958-0dc2-11e8-9047-d791c2a3d34e.png   ， 还有上面这个 图片 显示 不正常 在安卓 原生端     这个 问题可以解决嘛？

**Comment by songguangyu** [comment]
ios 默认是禁止视频自动播放的， 安卓原生的不同系统会给video 加一些默认图片，要解决这个问题，可以嵌入chrome 内核。 另外没有声音 是不是你设置静音播放了。

**Comment by soulToken** [comment]
您好， 可能我没有表达清楚，现在的问题是这样的  在麻烦您再 ios微信里面打开上面那个连接       加载视频的时候 一直处于加载状态， 必须手动点击播放 才能加载完全

**Comment by songguangyu** [comment]
https://github.com/Chimeejs/chimee-mobile-player/blob/master/doc/dev.md
可以看下这个文章 微信里需要调用微信sdk 来进行自动播放

**Comment by soulToken** [comment]
好的 谢谢了

**Comment by soulToken** [comment]
chimee (url) {
        var self=this;
          // src: 'http://cdn.toxicjohann.com/lostStar.mp4',
          var player=new ChimeeMobilePlayer({
              wrapper: '#wrapper',  // video dom容器
              src: url,
              autoplay: false,
              controls: true,
              playsInline: true,
              webkitPlaysInline:true,
              preload: true,
              x5VideoPlayerFullscreen: true,
              x5VideoOrientation: true,
              xWebkitAirplay: true,
              muted: true,
              penetrate:true
          });
          // player.exitFullscreen=function(){
          //   console.log(1)
          //   debugger;
          // }
        player.on('fullscreenchange', evt => 
        // console.log(evt)
        //将输入框取反
          setTimeout(function(){
              self.fullscreenchange=!self.fullscreenchange
          },100)
          
        )
        player.on('loadedmetadata', function() {
            self.durationTime=self.timeFormate(this.duration)
          }
        )


    },


我只是简单用了一下，  有一些不懂得地方， 比如， 控制条 前进 会稍微有点小问题， 这些插件里面应该有集成的吧？    具体可以打开上面那个网址看一下

**Comment by yandeqiang** [comment]
你在 body 元素上设置了一个 zoom： 0.5？

**Comment by soulToken** [comment]
<script>
            function bodyScale(){
                var devicewidth=document.documentElement.clientWidth
                var scale=devicewidth/750;
                //为了稍微适配 pc端,避免在pc端上过于难看
                if(scale > 1){
                  scale=1
                }
                document.body.style.zoom=scale;
            }
            bodyScale();
            window.onresize=function(){
                bodyScale();
            };	
        </script>

这段代码 ，自己封装的 js  ，写ui 的时候直接 用px 就行了  ，算是适配移动端的js 吧  这个 有问题嘛？

**Comment by songguangyu** [comment]
@yandeqiang  帮忙看一下

**Comment by soulToken** [comment]
![193724678757463489](https://user-images.githubusercontent.com/30686262/36625621-0fe4427c-195e-11e8-95c3-6b6d6c3b86e7.jpg)zheyan这样小屏播放时没有声音，  手机自带的反转全屏 之后 
![28501706239510300](https://user-images.githubusercontent.com/30686262/36625624-27a893a4-195e-11e8-9baf-2f3abc4c5c1b.jpg)  像这样 是有声音的， 上面的代码里面 没有静音播放啊

**Comment by songguangyu** [comment]
muted: true 是静音

**Comment by soulToken** [comment]
好的， 谢谢了

**Comment by Tolerantjz** [comment]
自动播放之后 声音怎么加起来呢    声音是和机器的声音同步这个 没作用啊 具体需要咋造作嘞  求解答

**Comment by yandeqiang** [comment]
移动端网页的声音一般都是和物理按键相关，手动设置 volume 无效。 app 内除外
