### ISSUE TITLE
how to trigger chimee event in all component

### ISSUE THREAD

**Issue by songguangyu** [Chimeejs/chimee#9]
same to title.

**Comment by toxic-johann** [comment]
额。。。题目有点宽。如果是这个题目的话应该是按照文档使用就好。

我觉得需要探讨的问题是，kernel 层如何模拟 video 事件。

我现在想到的方法是：

1. kernel 层直接在 dom 上利用 dispatchEvent 模拟事件
2. chimee 层暴露 trigger 事件给 kernel 层调用。

这两个方面有何利弊呢？

**video 模拟**

1. 方便，理论上大家都可以这么做
2. 但是会不会干扰到其他业务代码

**chimee 层模拟**

1. 如何提供，传递 bus 还是整个 dispatcher
2. 如何区分 kernel 和 plugin 层，或是否应该将这个能力也提供给 plugin 层。
