### ISSUE TITLE
chimee 所有相关的 js 加速问题？

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#90]
我们 cdn 的资源存放需要整理一下。

除了加入 cdnjs 的chimee 外其他部分也可以统一处理下。

例如统一放图床或者七牛等？毕竟 cdnjs 和爆米兔 cdn 加入比较麻烦

- [x] chimee (cdnjs)
- [x] chimee-player (baomitu cdn)
- [ ] chimee-kernel
- [ ] chimee-kernel-hls
- [ ] chimee-kernel-flv.js
- [ ] chimee-kernel-flv
- [ ] chimee-mobile-player
- [ ] chimee-plugin-popup

后面其他没有加的补充一下。我构建个 cli 在发版的时候上传一个源吧。

**Comment by trainliang** [comment]
chimee-mobile-player (baomihua cdn) 已添加

**Comment by toxic-johann** [comment]
使用 jsDelivr 即可 https://www.jsdelivr.com/?query=chimee
