### ISSUE TITLE
x5VideoPlayerType属性不起作用？

### ISSUE THREAD

**Issue by agileago** [Chimeejs/chimee#91]
发现在安卓网页上播放视频自动全屏，
```javascript
{
          autoplay: true,
          controls: true,
          playsInline: true,
          preload: true,
          x5VideoPlayerType: false,
          x5VideoPlayerFullscreen: false,
          x5VideoOrientation: false,
          xWebkitAirplay: false,
          muted: false
}
```
但还是会加上 `x5-video-player-type="h5"`这个属性导致播放时不能内联播放自动全屏了，另外再问一下这个配置在ios上面是不能自动播放么？必须要静音才能自动播放么？

**Comment by toxic-johann** [comment]
你用的 chimee 版本多少？

**Comment by agileago** [comment]
就是从chimee-mobile-player最新仓库下载的

**Comment by toxic-johann** [comment]
@yandeqiang chimee-mobile-player 中的 chimee 版本貌似没有更新？

![](https://ws4.sinaimg.cn/large/006tKfTcgy1focox37c3rj308z02ugll.jpg)

**Comment by yandeqiang** [comment]
已更新 chimee 
新版本中， 将 playsline / x5VideoPlayerType 两个属性分开设置了
