### ISSUE TITLE
Potential catastrophic backtracking vulnerability in ua-parser-js

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#92]
As there is Potential catastrophic backtracking vulnerability in ua-parser-js, we may consider change the library or wait for the library to fix the bug.

**Comment by songguangyu** [comment]
什么bug?

**Comment by toxic-johann** [comment]
> My name is James Davis. I'm a security researcher at Virginia Tech.
> The npm module chimee has 7 regular expressions vulnerable to catastrophic backtracking.
> The vulnerable expression is listed below.
> If you don't know, catastrophic backtracking is when the regex engine takes more than linear time to scan a string.
> There are lots of resources about it on the web. I have included some starting points below.
> Catastrophic backtracking is particularly problematic if two conditions are met:
> \1. The module is used by server processes, and
> \2. The regex can be reached by user input.
> Please evaluate whether these conditions apply to your users and your regexes.
> However, copy/pasting regexes is quite common. Even if one or both conditions fail now,
> these regexes may be a time bomb in your code for later -- you might still want to fix it.
> For example, if your module is used on the client side, consider whether a server-side counterpart might re-use this pattern later.
> Fix advice:
> If you want to make fixes, here are the most common approaches with examples:
> \1. Refactor the regex pattern
>    - <https://github.com/killmenot/valid-data-url/commit/64bad3cf1eff246103d71b51f945d7ea73bf7adf>
>    - <https://github.com/htmllint/htmllint/commit/eec921cee4327d7fe02ba6812bc39dc29f46b12a>
> \2. Replace the regex with custom parsing
>    - <https://github.com/jshttp/forwarded/commit/d469116eda4931fbe1c0ccb29497b35930bfa328>
>    - <https://github.com/kriskowal/q-io/commit/b9c54c809c48306835506a3baad5dab67bec9dab>
> \3. Apply input sanitization, suitable if legitimate input strings are (much) shorter than the attack string
>    - <https://github.com/hgoebl/mobile-detect.js/commit/7222f6e75cf8cd90e1dc53e445716203eaf79d8a>
>    - <https://github.com/node-modules/charset/commit/effda0c48c51b47a47f4cad7db0c51ee7407cc1b>
> You can study other examples using the links from Snyk.io's vulnerability database: <https://snyk.io/vuln/?packageManager=all>
> Validating your fix:
> \1. I am happy to test a refactored regex with my tools -- send me an email with the commit ID.
> \2. Existing GitHub projects for regex testing are:
>    - substack's safe-regex project (<https://github.com/substack/safe-regex>) -- easy to install, has false positives and some bugs
>    - Weideman's RegexStaticAnalysis project (<https://github.com/NicolaasWeideman/RegexStaticAnalysis>) -- a bit more work to install, may have false positives
> If this is a new topic for you, here are some good starting points for information:
> - <https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions>
> - <https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices#Backtracking>
> - <https://snyk.io/blog/redos-and-catastrophic-backtracking>
> ======================================
> Now, here are the vulnerable patterns with attack details.
> Each vulnerability has the following keys, explained in more detail below:
>  - pattern
>  - filesIn (as of December/January; I excluded any appearances in irrelevant-looking dirs, and in '.min' files)
>  - stringLenFor10Sec
>  - nPumpsFor10Sec
>  - attackFormat
>  - blowupCurve
> The attack format describes how to generate an attack string.
> On my machine, an attack string generated using nPumpsFor10Sec repetitions ("pumps") of the pump string(s)
> blocks the js regex engine for 10 seconds, though this will vary based on your hardware.
> Compose an attack string like this:
>   'prefix 1' + 'pump 1' X times + 'prefix 1' + 'pump 2' X times + ... + suffix
> Example:
>   With pumpPairs: [{'prefix': 'a', 'pump': 'b'}], suffix: 'c', an attack string with three pumps would be:
> ​    abbbc
> Catastrophic backtracking blows up at either an exponential rate or a super-linear (power law) rate.
> The blowupCurve indicates how severe the blow-up is.
> The 'type' is either EXP(onential) or POW(er law) in the number of pumps (x).
> The 'parms' are the parameters for the two curve types. The second parameter is more important, because:
>   EXP: f(x) = parms[0] * parms[1]^x
>   POW: f(x) = parms[0] * x^parms[1]
> I strongly recommend you address any EXP(onential) blow-ups.
> POW(er law) blow-ups vary in their severity depending on the value of the second parameter,
> and in the length of the attack string ('stringLenFor10Sec').
> But they are still a legitimate attack vector.
>
> I think you may have taken these from the ua-parser-js project. I have notified that project about their vulnerabilities as well.
>
> JSON formatted:
>
> Vuln 1:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "\t",

            "prefix" : "androidami\t"

         },

         {

            "pump" : "\t",

            "prefix" : "\t"

         }

      ],

      "suffix" : "_no"

   },

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "pattern" : "android.+(mi[\s\-]*(?:one|one[\s]plus|note lte)?[\s_]*(?:\d\w)?)\s+build",

   "blowupCurve" : {

      "r2" : 0.988980533580262,

      "type" : "POWER",

      "parms" : [

         2.46880695858972e-07,

         2.49214408841133

      ]

   },

   "stringLenFor10Sec" : 2355,

   "nPumpsFor10Sec" : "1170"

}

```


Vuln 2:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "\t",

            "prefix" : "androidaredmi\t"

         },

         {

            "pump" : "a",

            "prefix" : "\t"

         },

         {

            "pump" : "\t",

            "prefix" : "a"

         }

      ],

      "suffix" : "-"

   },

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "pattern" : "android.+(redmi[\s\-]*(?:note)?(?:[\s]*[\w\s]+)?)\s+build",

   "blowupCurve" : {

      "r2" : 0.997418474929402,

      "type" : "POWER",

      "parms" : [

         3.01942567217774e-08,

         3.49075936685764

      ]

   },

   "nPumpsFor10Sec" : "277",

   "stringLenFor10Sec" : 848

}

```

Vuln 3:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "(mobile;a",

            "prefix" : "mozillaa"

         },

         {

            "pump" : "geckoa",

            "prefix" : "a"

         }

      ],

      "suffix" : "e("

   },

   "pattern" : "mozilla.+\(mobile;.+gecko.+firefox",

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "blowupCurve" : {

      "r2" : 0.996516843338036,

      "type" : "POWER",

      "parms" : [

         8.69564442666123e-08,

         2.70507649410169

      ]

   },

   "nPumpsFor10Sec" : "966",

   "stringLenFor10Sec" : 14501

}
```

Vuln 4:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "\t",

            "prefix" : "androidami\t"

         },

         {

            "pump" : "a",

            "prefix" : "\t"

         },

         {

            "pump" : "\t",

            "prefix" : "a"

         }

      ],

      "suffix" : "-m"

   },

   "pattern" : "android.+(mi[\s\-]*(?:pad)?(?:[\s]*[\w\s]+)?)\s+build",

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "stringLenFor10Sec" : 930,

   "blowupCurve" : {

      "r2" : 0.989228652472189,

      "type" : "POWER",

      "parms" : [

         1.59657452970297e-07,

         3.15127502189794

      ]

   },

   "nPumpsFor10Sec" : "305"

}

```


Vuln 5:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "lga",

            "prefix" : "androida"

         }

      ],

      "suffix" : "ui"

   },

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "pattern" : "android.+lg(\-?[\d\w]+)\s+build",

   "stringLenFor10Sec" : 159484,

   "blowupCurve" : {

      "r2" : 0.992519180880472,

      "type" : "POWER",

      "parms" : [

         7.04862905895594e-10,

         2.15276248362914

      ]

   },

   "nPumpsFor10Sec" : "53158"

}

```


Vuln 6:

```
{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "a",

            "prefix" : "opera\ta"

         }

      ],

      "suffix" : "\t"

   },

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "pattern" : "(opera\s[mobiletab]+).+version\/([\w\.-]+)",

   "blowupCurve" : {

      "r2" : 0.996884634415012,

      "type" : "POWER",

      "parms" : [

         1.08388004075772e-08,

         1.85123425412764

      ]

   },

   "nPumpsFor10Sec" : "70755",

   "stringLenFor10Sec" : 70763

}

```

```
Vuln 7:

{

   "attackFormat" : {

      "pumpPairs" : [

         {

            "pump" : "\t",

            "prefix" : "androidahm\tnote\t"

         }

      ],

      "suffix" : "b\t"

   },

   "pattern" : "android.+(hm[\s\-]*note?[\s]*(?:\d\w)?)\s+build",

   "filesIn" : [

      [

         "lib/index.min.js",

         "lib/index.browser.js"

      ]

   ],

   "blowupCurve" : {

      "r2" : 0.996860265204259,

      "type" : "POWER",

      "parms" : [

         1.1932193801731e-08,

         1.85816180712193

      ]

   },

   "nPumpsFor10Sec" : "64322",

   "stringLenFor10Sec" : 64340

}

```

Best,

James

**Comment by songguangyu** [comment]
额 都是ua的正则 这个他有检测的工具吗？我们更换了之后能进行检测吗？

**Comment by toxic-johann** [comment]
有的。慢慢来吧。。这个事情不急。看看 ua-parser-js 会不会升级。

**Comment by songguangyu** [comment]
嗯
