### ISSUE TITLE
MediaSource onSourceEnded 事件暴露

### ISSUE THREAD

**Issue by jinyang1994** [Chimeejs/chimee#93]
我想修改默认的提示语，不过我没找到对应的文档。具体要怎么修改呢？

**Comment by toxic-johann** [comment]
你使用的是 chimee-player 吗？

**Comment by jinyang1994** [comment]
是的，里面有一句加载失败，刷新重试的那句话

**Comment by toxic-johann** [comment]
@yandeqiang @huzunjie  这方面有做吗？

**Comment by jinyang1994** [comment]
我看到这个是`chimee-plugin-center-state`，如果暂时解决不了，我是可以自己`fork`一份，引用自己的插件的是吧？

**Comment by toxic-johann** [comment]
是的可以的。

**Comment by jinyang1994** [comment]
还有一个小疑问，我如何监控直播关闭后的MediaSource onSourceEnded 事件。

**Comment by toxic-johann** [comment]
你用的是哪个 kernel 呢？

**Comment by toxic-johann** [comment]
或者播放是什么视频流？

**Comment by jinyang1994** [comment]
`flv`和`hls`都会用到。

**Comment by jinyang1994** [comment]
是这样的，移动端我们也会采用你们提供的`chimee-mobile-player`版本。PC上用`flv`，移动端用`hls`。不过我可以直接在移动端上面也使用`chimee-player`，如果这样用的话，会出现什么问题么？

**Comment by toxic-johann** [comment]
chimee-player 体积比较大，移动端直接用 native 就好。不需要用 hls。

@songguangyu 看一下那个事件是否需要额外暴露的？

**Comment by yandeqiang** [comment]
主要是拖动进度条用不了。。。
刚才更新了一下 chimee-plugin-center-state 增加配置参数 errorTips

**Comment by jinyang1994** [comment]
你们的处理速度真的是让人感动到哭，谢谢🙏

**Comment by jinyang1994** [comment]
打扰一下，那个事件有暴露出来么？还有一个问题，flv模式中Safari有的时候会卡在第一帧，然后需要过15秒之后点前进按钮才能继续播放，这个问题是？

**Comment by jinyang1994** [comment]
谢谢，期待这个事件的暴露。

**Comment by songguangyu** [comment]
@jinyang1994  sourceEnd 直播应该没有严格的结束，可能需要用户手动判断，chimee里 可以监听 heartbeat事件，拿到流的下载速度，你可以判断在3秒内都没有流进来的话 就判断是直播结束了。

**Comment by jinyang1994** [comment]
@songguangyu hls 可以监听心跳么？

**Comment by toxic-johann** [comment]
不是，只有 chimee-kernel-flv 有。

**Comment by jinyang1994** [comment]
那hls里面有类似的么？
