### ISSUE TITLE
pc端 m3u8，任意点播时间，跳转恢复失败，页面提示请求失败

### ISSUE THREAD

**Issue by trainliang** [Chimeejs/chimee#98]
## 级别
重大Bug
## bug 版本
chiemm-player:1.3.1(20180304版)
## 问题现象
pc端 m3u8，随便点击中间时间，然后页面提示请求失败
## bug概率
100%

**Comment by toxic-johann** [comment]
排查可能发生问题的环节

- [x] chimee-kernel-hls
- [ ] chimee-kernel
- [ ]  chimee
- [ ] chimee-player

**Comment by toxic-johann** [comment]
问题原因应是 chimee 接收到 chimee-kernel 的错误后抛出到全局，阻塞了后方的应用持续执行。

**Comment by toxic-johann** [comment]
涉及相关 package

- [ ] chimee
- [ ] chimee-player
- [ ] chimee-mobile-player
